"""
Which folding pass each census row owes its rewrite to, measured by neutering one pass at a time.

`refinery.lib.scripts.ps1.deobfuscation.fold_census.FOLDS` records what the tool makes of a row;
this records why. A row is `lost` for a pass when neutering that pass stops the row being rewritten
at all, and `changed` when the row is still rewritten but to something else. A row can be lost for
more than one pass, because the two may each be necessary.

The rows are held rather than counted: a count moves when a fold is lost and moves back when an
unrelated one is gained, so a pass that swaps what it contributes reads as no change. Here each row
is named, and a swap is a diff.

A pass with two empty buckets contributes nothing to the corpus. That is a fact about the corpus and
not about the pass — it holds no flattened control flow, and no expandable string that survives
hoisting into the output — and the emptiness is recorded so that a corpus row which starts
exercising one has to say so.
"""
from __future__ import annotations

import typing


class Contribution(typing.NamedTuple):
    #: Rows that stop being rewritten at all without the pass.
    lost: tuple[str, ...]
    #: Rows that are still rewritten without the pass, but to something else.
    changed: tuple[str, ...]


CONTRIBUTION: dict[str, Contribution] = {
    'Ps1SuccessFlagInlining': Contribution(
        lost=(),
        changed=(),
    ),
    'Ps1ConstantFolding': Contribution(
        lost=(
            "$t = '1e400' + 1; Write-Output (,$t); Write-Output $t",
            "$t = '5' * 2; Write-Output (,$t); Write-Output $t",
            "$t = '5' + 5; Write-Output (,$t); Write-Output $t",
            "$t = '5' - 1; Write-Output (,$t); Write-Output $t",
            "$t = '5' / 2; Write-Output (,$t); Write-Output $t",
            "$t = 'A' -ceq 'a'; Write-Output (,$t); Write-Output $t",
            "$t = 'A' -ieq 'a'; Write-Output (,$t); Write-Output $t",
            "$t = 'AB'.Count; Write-Output (,$t); Write-Output $t",
            "$t = 'AB'.Length; Write-Output (,$t); Write-Output $t",
            "$t = 'AB'.Zqnope; Write-Output (,$t)",
            "$t = 'ABC'[0]; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + -1.50d; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + 0.5d; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + 1.50d; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + 1.5; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + 1L; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + 1e3d; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + 79228162514264337593543950335d; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + [char]65; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + [uint64]18446744073709551615; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 0.0d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 1.000d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 1.00d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 1.0d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 1.100d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 1.10d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 1.2300d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 10.0d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 2.0d; Write-Output (,$t); Write-Output $t",
            '$t = (5).Count; Write-Output (,$t); Write-Output $t',
            '$t = (5).Length; Write-Output (,$t); Write-Output $t',
            '$t = (5).Rank; Write-Output (,$t)',
            '$t = (5).Zqnope; Write-Output (,$t)',
            '$t = ([char]65).ToString(); Write-Output (,$t); Write-Output $t',
            "$t = - ' 5 '; Write-Output (,$t); Write-Output $t",
            "$t = - ''; Write-Output (,$t); Write-Output $t",
            "$t = - '0'; Write-Output (,$t); Write-Output $t",
            "$t = - '1e3'; Write-Output (,$t); Write-Output $t",
            "$t = - '5'; Write-Output (,$t); Write-Output $t",
            '$t = - 0.0; Write-Output (,$t); Write-Output $t',
            '$t = - 0.0d; Write-Output (,$t); Write-Output $t',
            '$t = - 0; Write-Output (,$t); Write-Output $t',
            '$t = - 0d; Write-Output (,$t); Write-Output $t',
            '$t = - 1.00d; Write-Output (,$t); Write-Output $t',
            '$t = - 1.0d; Write-Output (,$t); Write-Output $t',
            '$t = - 1.10d; Write-Output (,$t); Write-Output $t',
            '$t = - 1.5; Write-Output (,$t); Write-Output $t',
            '$t = - 1.5d; Write-Output (,$t); Write-Output $t',
            '$t = - 2147483647; Write-Output (,$t); Write-Output $t',
            '$t = - 2147483648; Write-Output (,$t); Write-Output $t',
            '$t = - 5; Write-Output (,$t); Write-Output $t',
            '$t = - 79228162514264337593543950335d; Write-Output (,$t); Write-Output $t',
            '$t = - 9223372036854775807L; Write-Output (,$t); Write-Output $t',
            '$t = - [byte]5; Write-Output (,$t); Write-Output $t',
            '$t = - [char]0; Write-Output (,$t); Write-Output $t',
            '$t = - [char]65; Write-Output (,$t); Write-Output $t',
            '$t = - [uint32]1; Write-Output (,$t); Write-Output $t',
            '$t = - [uint64]18446744073709551615; Write-Output (,$t); Write-Output $t',
            '$t = -1 * [uint64]1; Write-Output (,$t); Write-Output $t',
            '$t = -2147483647 - 1; Write-Output (,$t); Write-Output $t',
            '$t = -2147483648 % -1; Write-Output (,$t); Write-Output $t',
            '$t = -2147483648 - 9223372036854775807L; Write-Output (,$t); Write-Output $t',
            '$t = -2147483648 / -1; Write-Output (,$t); Write-Output $t',
            "$t = 0 + '5'; Write-Output (,$t); Write-Output $t",
            '$t = 0 + [char]65; Write-Output (,$t); Write-Output $t',
            '$t = 0 - [uint64]18446744073709551615; Write-Output (,$t); Write-Output $t',
            '$t = 0 -or 0; Write-Output (,$t); Write-Output $t',
            '$t = 0xFFFFFFFF + 0; Write-Output (,$t); Write-Output $t',
            '$t = 0xFFFFFFFFFFFFFFFF + 0; Write-Output (,$t); Write-Output $t',
            "$t = 1 + '  '; Write-Output (,$t); Write-Output $t",
            "$t = 1 + ' 7 '; Write-Output (,$t); Write-Output $t",
            "$t = 1 + '+5'; Write-Output (,$t); Write-Output $t",
            "$t = 1 + '0xFFFFFFFF'; Write-Output (,$t); Write-Output $t",
            "$t = 1 + '1.5L'; Write-Output (,$t); Write-Output $t",
            "$t = 1 + '1e3'; Write-Output (,$t); Write-Output $t",
            "$t = 1 + '1kb'; Write-Output (,$t); Write-Output $t",
            "$t = 1 + '2147483648'; Write-Output (,$t); Write-Output $t",
            "$t = 1 + '5'; Write-Output (,$t); Write-Output $t",
            "$t = 1 + 'AB'.Count; Write-Output (,$t); Write-Output $t",
            '$t = 1 + [uint64]18446744073709551615; Write-Output (,$t); Write-Output $t',
            "$t = 1 - '5'; Write-Output (,$t); Write-Output $t",
            '$t = 1 -and 0; Write-Output (,$t); Write-Output $t',
            '$t = 1 -and 2; Write-Output (,$t); Write-Output $t',
            '$t = 1 -ceq 1; Write-Output (,$t); Write-Output $t',
            '$t = 1 / [uint64]18446744073709551615; Write-Output (,$t); Write-Output $t',
            '$t = 1.000d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.00d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.0d * 1d; Write-Output (,$t); Write-Output $t',
            '$t = 1.0d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.0d + 2.0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.0d - 0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.0d / 1d; Write-Output (,$t); Write-Output $t',
            '$t = 1.100d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.10d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.2345678901234567890123456789d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.5 * [char]48; Write-Output (,$t); Write-Output $t',
            '$t = 1.500d + 1.500d; Write-Output (,$t); Write-Output $t',
            '$t = 1.50d + 1.50d; Write-Output (,$t); Write-Output $t',
            '$t = 100000000000000d * 100000000000000d; Write-Output (,$t); Write-Output $t',
            '$t = 10d + 0; Write-Output (,$t); Write-Output $t',
            "$t = 12 + '0xabc'; Write-Output (,$t); Write-Output $t",
            '$t = 1L + 0; Write-Output (,$t); Write-Output $t',
            '$t = 1d / 3d; Write-Output (,$t); Write-Output $t',
            '$t = 1kb + 0; Write-Output (,$t); Write-Output $t',
            '$t = 2 * [char]48; Write-Output (,$t); Write-Output $t',
            '$t = 2.50d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 2147483647 * 2147483647; Write-Output (,$t); Write-Output $t',
            '$t = 2147483647 * [uint32]4294967295; Write-Output (,$t); Write-Output $t',
            '$t = 2147483647 + 1; Write-Output (,$t); Write-Output $t',
            "$t = 5 + '5'; Write-Output (,$t); Write-Output $t",
            '$t = 512MB * 512MB; Write-Output (,$t); Write-Output $t',
            '$t = 79228162514264337593543950334d + 1d; Write-Output (,$t); Write-Output $t',
            '$t = 79228162514264337593543950335d * 1d; Write-Output (,$t); Write-Output $t',
            '$t = 79228162514264337593543950335d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 79228162514264337593543950335d - 1d; Write-Output (,$t); Write-Output $t',
            '$t = 79228162514264337593543950335d / 1d; Write-Output (,$t); Write-Output $t',
            '$t = 9223372036854775807 + 2; Write-Output (,$t); Write-Output $t',
            '$t = 9223372036854775807L + 1; Write-Output (,$t); Write-Output $t',
            '$t = 9223372036854775807L - -1L; Write-Output (,$t); Write-Output $t',
            '$t = @() * 5000; Write-Output (,$t); Write-Output $t.Count',
            '$t = @() + 1; Write-Output (,$t); Write-Output $t.Count',
            '$t = @(1, 2) * 0; Write-Output (,$t); Write-Output $t.Count',
            '$t = @(1, 2) * 2; Write-Output (,$t); Write-Output $t.Count',
            "$t = @(1, 2) + 'a'; Write-Output (,$t); Write-Output $t.Count",
            '$t = @(1, 2) + 5; Write-Output (,$t); Write-Output $t.Count',
            '$t = @(1, 2) + @(3, 4); Write-Output (,$t); Write-Output $t.Count',
            '$t = @(1, 2, 3).Count; Write-Output (,$t); Write-Output $t',
            '$t = @(1, 2, 3).Length; Write-Output (,$t); Write-Output $t',
            '$t = @(1, 2, 3).Rank; Write-Output (,$t); Write-Output $t',
            "$t = [Convert]::ToByte('FF', 16); Write-Output (,$t); Write-Output $t",
            '$t = [Convert]::ToChar(65); Write-Output (,$t); Write-Output $t',
            "$t = [Convert]::ToInt32(' 5 '); Write-Output (,$t); Write-Output $t",
            "$t = [Convert]::ToInt32('017', 8); Write-Output (,$t); Write-Output $t",
            "$t = [Convert]::ToInt32('80000000', 16); Write-Output (,$t); Write-Output $t",
            "$t = [Convert]::ToInt32('FFFFFFFF', 16); Write-Output (,$t); Write-Output $t",
            '$t = [Convert]::ToInt32(1.5); Write-Output (,$t); Write-Output $t',
            '$t = [Convert]::ToInt32(1.5d); Write-Output (,$t); Write-Output $t',
            '$t = [Convert]::ToInt64(5); Write-Output (,$t); Write-Output $t',
            '$t = [byte](200 * 2); Write-Output (,$t); Write-Output $t',
            "$t = [char]48 - '1'; Write-Output (,$t); Write-Output $t",
            '$t = [char]48 - 0.0; Write-Output (,$t); Write-Output $t',
            '$t = [char]65 -ceq [char]97; Write-Output (,$t); Write-Output $t',
            '$t = [uint64]18446744073709551615 + 1; Write-Output (,$t); Write-Output $t',
            "$t = if (- '0') { 'yes' } else { 'no' }; Write-Output (,$t); Write-Output $t",
            "$t = if (- '5') { 'yes' } else { 'no' }; Write-Output (,$t); Write-Output $t",
            '$v = \'a\'; . ([ScriptBlock]::Create(\'$v = "b"\')); Write-Output $v; Write-Output (1 + 1)',
            '$x = (1).5',
            '$x = 1e3.5',
            '$x = 3..5',
            "$z = 1.000d; $t = 'x' + $z; Write-Output (,$t); Write-Output $t",
            "$z = 1.00d; $t = 'x' + $z; Write-Output (,$t); Write-Output $t",
            "$z = 1.0d; $t = 'x' + $z; Write-Output (,$t); Write-Output $t",
            "&('Write' + '-Output') 'indirect'",
            "'ABC'.ToLower()",
            "'a' * 3",
            "'a' + 'b'",
            "'a{0}c' -f 'b'",
            "'{0}-{1}' -f 'a', 'b'",
            '1 + 2',
            '1..2',
            '1..3 | ForEach-Object { $_ * 2 }',
            "Update-TypeData -Force -TypeName System.String -MemberName Length -MemberType ScriptProperty -Value { 99 }; Write-Host 'abc'.Length",
            "Update-TypeData -TypeName System.String -MemberName Zq -MemberType ScriptProperty -Value { Write-Host 'S' }; $Null = 'abc'.Zq; Write-Host 'A'",
            "Write-Host 'abc'.Length",
            'Write-Output "abc".Length',
            "Write-Output 'abc'.Length",
            "Write-Output ('A' * 3)",
            "Write-Output ('xyx'.Replace([char]120, [char]122)); Write-Output ('xyx'.Replace('x', 'z'))",
            "Write-Output ('{0}' -f [char]65); Write-Output ('{0}' -f 'A')",
            'Write-Output ((5).PSTypeNames)',
            "Write-Output (1 + [char]65); Write-Output (1 + 'A')",
            "Write-Output ([char]114 + [char]53); Write-Output ('r' + '5')",
            "Write-Output ([char]65 + 1); Write-Output ('A' + 1)",
            "[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('aGk='))",
            "[string]::Join('', ('a', 'b'))",
            "foreach ($i in 1..2) { Write-Output $($c = $c + 'x'; $c) }",
            'foreach ($i in 1..2) { Write-Output $(if (0) { $m = \'A\' }; $o = "${m}"; $m = \'B\'; $o) }',
            "trap { continue }; foreach ($i in 1..2) { throw 'e'; Write-Host 'tail' }; Write-Host 'next'",
        ),
        changed=(
            '$a = $null; $b = 5; $t = $a * $b; Write-Output (,$t)',
            '$a = $null; $t = $a * 5; Write-Output (,$t)',
            "$a = 'a,b,c' -split ',', 2; $t = $a.Count; Write-Output (,$t); Write-Output $t",
            "$a = 'a,b,c' -split ',', 2; $t = $a[1]; Write-Output (,$t); Write-Output $t",
            '$a = 1; $b = 2; $a + $b',
            '$null -eq $undefined',
            '$p = @(@(1, 2), @(3, 4)); $q = $p[0]; $q[0] = 9; Write-Output $p[0][0]',
            "$s = 'abc'; $s.Substring(1, 2)",
            "$s = 'abcd'; $t = $s; $t = 1, 2, 3; [Array]::Reverse($t); Write-Output $s.Length",
            '$t = $false + 1; Write-Output (,$t); Write-Output $t',
            '$t = $false -eq $null; Write-Output (,$t); Write-Output $t',
            '$t = $false -eq 0; Write-Output (,$t); Write-Output $t',
            '$t = $false -gt $null; Write-Output (,$t); Write-Output $t',
            '$t = $false -lt 5; Write-Output (,$t); Write-Output $t',
            '$t = $null * 1; Write-Output (,$t)',
            '$t = $null + $true; Write-Output (,$t); Write-Output $t',
            "$t = $null + 'abc'; Write-Output (,$t); Write-Output $t",
            '$t = $null + 1.5d; Write-Output (,$t); Write-Output $t',
            '$t = $null + 5; Write-Output (,$t); Write-Output $t',
            '$t = $null + @(1, 2); Write-Output (,$t); Write-Output $t.Count',
            '$t = $null + [char]65; Write-Output (,$t); Write-Output $t',
            '$t = $null - 5; Write-Output (,$t); Write-Output $t',
            '$t = $null -band 1; Write-Output (,$t); Write-Output $t',
            '$t = $null -eq $false; Write-Output (,$t); Write-Output $t',
            '$t = $null -eq $null; Write-Output (,$t); Write-Output $t',
            "$t = $null -eq ''; Write-Output (,$t); Write-Output $t",
            '$t = $null -eq 0; Write-Output (,$t); Write-Output $t',
            '$t = $null -ge 1; Write-Output (,$t); Write-Output $t',
            '$t = $null -gt -5; Write-Output (,$t); Write-Output $t',
            '$t = $null -gt 1; Write-Output (,$t); Write-Output $t',
            '$t = $null -le -5; Write-Output (,$t); Write-Output $t',
            '$t = $null -le 1; Write-Output (,$t); Write-Output $t',
            "$t = $null -lt ''; Write-Output (,$t); Write-Output $t",
            "$t = $null -lt 'abc'; Write-Output (,$t); Write-Output $t",
            '$t = $null -lt -5; Write-Output (,$t); Write-Output $t',
            '$t = $null -lt 0; Write-Output (,$t); Write-Output $t',
            '$t = $null -lt 1; Write-Output (,$t); Write-Output $t',
            '$t = $null -ne $null; Write-Output (,$t); Write-Output $t',
            '$t = $null -ne 0; Write-Output (,$t); Write-Output $t',
            '$t = $null -or $false; Write-Output (,$t); Write-Output $t',
            '$t = $null.Count; Write-Output (,$t); Write-Output $t',
            '$t = $true * 1.5d; Write-Output (,$t); Write-Output $t',
            '$t = $true + $true; Write-Output (,$t); Write-Output $t',
            "$t = $true + ''; Write-Output (,$t); Write-Output $t",
            '$t = $true + 1.5; Write-Output (,$t); Write-Output $t',
            '$t = $true + 1; Write-Output (,$t); Write-Output $t',
            '$t = $true + 9223372036854775807L; Write-Output (,$t); Write-Output $t',
            '$t = $true - 1.5; Write-Output (,$t); Write-Output $t',
            '$t = $true - 1; Write-Output (,$t); Write-Output $t',
            '$t = $true -and $true; Write-Output (,$t); Write-Output $t',
            "$t = $true -and ''; Write-Output (,$t); Write-Output $t",
            '$t = $true -and @(); Write-Output (,$t); Write-Output $t',
            '$t = $true -and [char]0; Write-Output (,$t); Write-Output $t',
            '$t = $true -band 1; Write-Output (,$t); Write-Output $t',
            '$t = $true -bxor $false; Write-Output (,$t); Write-Output $t',
            '$t = $true -eq $null; Write-Output (,$t); Write-Output $t',
            "$t = $true -eq ''; Write-Output (,$t); Write-Output $t",
            "$t = $true -eq '0'; Write-Output (,$t); Write-Output $t",
            "$t = $true -eq 'abc'; Write-Output (,$t); Write-Output $t",
            '$t = $true -eq 1; Write-Output (,$t); Write-Output $t',
            '$t = $true -eq 2; Write-Output (,$t); Write-Output $t',
            "$t = $true -ge 'abc'; Write-Output (,$t); Write-Output $t",
            '$t = $true -gt $false; Write-Output (,$t); Write-Output $t',
            '$t = $true -gt 2; Write-Output (,$t); Write-Output $t',
            '$t = $true -lt 2; Write-Output (,$t); Write-Output $t',
            '$t = $true -ne 2; Write-Output (,$t); Write-Output $t',
            '$t = $true -xor $true; Write-Output (,$t); Write-Output $t',
            '$t = $true / 1; Write-Output (,$t); Write-Output $t',
            "$t = ' ' -and $true; Write-Output (,$t); Write-Output $t",
            "$t = '' -eq $null; Write-Output (,$t); Write-Output $t",
            "$t = '' -eq '0'; Write-Output (,$t); Write-Output $t",
            "$t = '' -eq 0; Write-Output (,$t); Write-Output $t",
            "$t = '' -gt $null; Write-Output (,$t); Write-Output $t",
            "$t = '' -or $false; Write-Output (,$t); Write-Output $t",
            "$t = '0' -and $true; Write-Output (,$t); Write-Output $t",
            "$t = '0' -eq 0; Write-Output (,$t); Write-Output $t",
            "$t = '1.0' -eq 1; Write-Output (,$t); Write-Output $t",
            "$t = '10' -band 6; Write-Output (,$t); Write-Output $t",
            "$t = '10' -ne 10; Write-Output (,$t); Write-Output $t",
            "$t = '1000' -eq 1e3d; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + $false; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + $null; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + $true; Write-Output (,$t); Write-Output $t",
            "$t = 'a-b-c' -split '-' | ForEach-Object { $_ }; Write-Output (,$t)",
            "$t = 'abc' -and $true; Write-Output (,$t); Write-Output $t",
            "$t = 'abc' -eq $true; Write-Output (,$t); Write-Output $t",
            "$t = 'abc' -lt $null; Write-Output (,$t); Write-Output $t",
            "$t = 'abc' -replace '(?<x>b)', '[${x}]'; Write-Output (,$t); Write-Output $t",
            "$t = 'false' -and $true; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + (1.0d); Write-Output (,$t); Write-Output $t",
            "$t = ('A').Substring(0); Write-Output (,$t); Write-Output $t",
            "$t = ('A').ToUpper(); Write-Output (,$t); Write-Output $t",
            '$t = (,$true) -and $true; Write-Output (,$t); Write-Output $t',
            "$t = (,' ') -and $true; Write-Output (,$t); Write-Output $t",
            "$t = (,'') -and $true; Write-Output (,$t); Write-Output $t",
            "$t = (,'a') -and $true; Write-Output (,$t); Write-Output $t",
            '$t = (,(,(,0))) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,(,0)) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,(,@())) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,0.0) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,0.0d) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,1) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,@()) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,@(1, 2)) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,[char]0) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,[char]65) -and $true; Write-Output (,$t); Write-Output $t',
            "$t = (- '0') -and $true; Write-Output (,$t); Write-Output $t",
            '$t = (1, 2), 3; Write-Output (,$t); Write-Output $t.Count',
            '$t = , 1; Write-Output (,$t); Write-Output $t.Count',
            '$t = ,(1, 2); Write-Output (,$t); Write-Output $t.Count',
            '$t = - $false; Write-Output (,$t); Write-Output $t',
            '$t = - $null; Write-Output (,$t); Write-Output $t',
            '$t = - $true; Write-Output (,$t); Write-Output $t',
            '$t = - (-2147483648); Write-Output (,$t); Write-Output $t',
            '$t = -(2147483647); Write-Output (,$t); Write-Output $t',
            '$t = -(2147483648); Write-Output (,$t); Write-Output $t',
            '$t = -0.0 -or $false; Write-Output (,$t); Write-Output $t',
            '$t = -1 -band [uint32]1; Write-Output (,$t); Write-Output $t',
            '$t = -bnot $null; Write-Output (,$t); Write-Output $t',
            '$t = -bnot $true; Write-Output (,$t); Write-Output $t',
            "$t = -bnot '5'; Write-Output (,$t); Write-Output $t",
            '$t = -bnot 0xFF; Write-Output (,$t); Write-Output $t',
            '$t = -bnot 0xFFFFFFFF; Write-Output (,$t); Write-Output $t',
            '$t = -bnot 1.5; Write-Output (,$t); Write-Output $t',
            '$t = -bnot 10d; Write-Output (,$t); Write-Output $t',
            '$t = -bnot 1L; Write-Output (,$t); Write-Output $t',
            '$t = -bnot [byte]5; Write-Output (,$t); Write-Output $t',
            '$t = -bnot [char]65; Write-Output (,$t); Write-Output $t',
            '$t = -bnot [uint32]7; Write-Output (,$t); Write-Output $t',
            "$t = -not '0'; Write-Output (,$t); Write-Output $t",
            '$t = -not (,[char]0); Write-Output (,$t); Write-Output $t',
            "$t = -not (- '0'); Write-Output (,$t); Write-Output $t",
            '$t = -not @(); Write-Output (,$t); Write-Output $t',
            '$t = -not @(0); Write-Output (,$t); Write-Output $t',
            '$t = -not [char]0; Write-Output (,$t); Write-Output $t',
            '$t = 0 -eq $null; Write-Output (,$t); Write-Output $t',
            "$t = 0 -eq '0'; Write-Output (,$t); Write-Output $t",
            '$t = 0 -gt $null; Write-Output (,$t); Write-Output $t',
            '$t = 0.0 -or $false; Write-Output (,$t); Write-Output $t',
            '$t = 0.0d -or $false; Write-Output (,$t); Write-Output $t',
            '$t = 0L -or $false; Write-Output (,$t); Write-Output $t',
            '$t = 0xFFFFFFFF -bxor 0x5A; Write-Output (,$t); Write-Output $t',
            '$t = 1 + $true; Write-Output (,$t); Write-Output $t',
            '$t = 1 - $true; Write-Output (,$t); Write-Output $t',
            "$t = 1 -eq '1.0'; Write-Output (,$t); Write-Output $t",
            '$t = 1 -ge $null; Write-Output (,$t); Write-Output $t',
            '$t = 1 -gt $null; Write-Output (,$t); Write-Output $t',
            '$t = 1 -le $null; Write-Output (,$t); Write-Output $t',
            '$t = 1 -lt $null; Write-Output (,$t); Write-Output $t',
            '$t = 1 -ne $null; Write-Output (,$t); Write-Output $t',
            '$t = 1.0d - $true; Write-Output (,$t); Write-Output $t',
            '$t = 1.5d -and $true; Write-Output (,$t); Write-Output $t',
            '$t = 10 - $null + 3; Write-Output (,$t); Write-Output $t',
            '$t = 10 - $null; Write-Output (,$t); Write-Output $t',
            "$t = 10 -ne '10'; Write-Output (,$t); Write-Output $t",
            '$t = 10 -ne 20; Write-Output (,$t); Write-Output $t',
            '$t = 10, 20, 30 -eq 20; Write-Output (,$t); Write-Output $t',
            '$t = 10, 20, 30, 20, 10 -ne 20; Write-Output (,$t); Write-Output $t',
            '$t = 1L -shl 64; Write-Output (,$t); Write-Output $t',
            '$t = 2 * $true; Write-Output (,$t); Write-Output $t',
            '$t = 2 -eq $true; Write-Output (,$t); Write-Output $t',
            '$t = 5 -xor 0; Write-Output (,$t); Write-Output $t',
            '$t = 65, 66 | ForEach-Object { [char]$_ }; Write-Output $t.Count; Write-Output $t',
            '$t = @($false) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = @($null) -and $true; Write-Output (,$t); Write-Output $t',
            "$t = @('a', 'b') | ForEach-Object { $_ }; Write-Output ($t -join '-')",
            '$t = @((1, 2)); Write-Output (,$t); Write-Output $t.Count',
            '$t = @() -or $false; Write-Output (,$t); Write-Output $t',
            '$t = @(); Write-Output (,$t); Write-Output $t.Count',
            '$t = @(0) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = @(0, 0) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = @(1, 2) + $null; Write-Output (,$t); Write-Output $t.Count',
            '$t = @(1, 2) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = @(1, 2) -eq $null; Write-Output (,$t); Write-Output $t',
            '$t = @(1, 2, 3) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = @(@()) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = @(@(1, 2)); Write-Output (,$t); Write-Output $t.Count',
            '$t = @(@(1, 2), 3); Write-Output (,$t); Write-Output $t.Count',
            '$t = [Convert]::ToInt32($null); Write-Output (,$t); Write-Output $t',
            '$t = [byte]0 -or $false; Write-Output (,$t); Write-Output $t',
            "$t = [char[]]'ABC'; Write-Output (,$t); Write-Output $t.Count",
            "$t = [char]'0' -and $true; Write-Output (,$t); Write-Output $t",
            '$t = [char]0 -or $false; Write-Output (,$t); Write-Output $t',
            '$t = [char]48 -band [byte]255; Write-Output (,$t); Write-Output $t',
            '$t = [char]48 -bxor [char]48; Write-Output (,$t); Write-Output $t',
            "$t = [char]48 -eq '0'; Write-Output (,$t); Write-Output $t",
            '$t = [char]48 -eq 48; Write-Output (,$t); Write-Output $t',
            '$t = [char]65 -and $true; Write-Output (,$t); Write-Output $t',
            '$t = [char]65 -bxor 32; Write-Output (,$t); Write-Output $t',
            '$t = [char]65 -eq [char]97; Write-Output (,$t); Write-Output $t',
            '$t = [char]65 -lt [char]97; Write-Output (,$t); Write-Output $t',
            '$t = [char]97 -lt [char]66; Write-Output (,$t); Write-Output $t',
            '$t = [uint64]0 -or $false; Write-Output (,$t); Write-Output $t',
            '$v = \'a\'; & ([ScriptBlock]::Create(\'$v + "b"\')); Write-Output (1 + 1)',
            '$v = \'a\'; & ([ScriptBlock]::Create(\'$v = "b"\')); Write-Output $v; Write-Output (1 + 1)',
            '$x = $($r = [byte]77; $r); Write-Output ($x -is [byte])',
            '$x = $($r = [char]66; $r); Write-Output ($x -is [char])',
            '$x = \'a\'; &(\'i\' + \'ex\') \'$x = "b"\'; Write-Host $x',
            "$x = 'a'; 1..2 | ForEach-Object { Write-Host $x }; $x = 'c'",
            '$z = 1.100d; $t = $z + 0d; Write-Output (,$t); Write-Output $t',
            "$z = 1.100d; $t = 'x' + $z; Write-Output (,$t); Write-Output $t",
            "$z = 1.10d; $t = 'x' + $z; Write-Output (,$t); Write-Output $t",
            '$z = 1.50d; $t = $z + 1.50d; Write-Output (,$t); Write-Output $t',
            "('a', 'b', 'c') -join ''",
            '-not $x',
            "Write-Output ('a,b' -split [char]44); Write-Output ('a,b' -split ',')",
            "Write-Output ('x' -replace 'x', [char]65); Write-Output ('x' -replace 'x', 'A')",
            "Write-Output (('AB').PSTypeNames)",
            "Write-Output (([char]65).Count); Write-Output (('A').Count)",
            "Write-Output (([char]65).Length); Write-Output (('A').Length)",
            "Write-Output (([char]65).ToString()); Write-Output (('A').ToString())",
            "Write-Output (([char]65, [char]66) -join ''); Write-Output (('A', 'B') -join '')",
            "Write-Output ([char[]](72, 73) -is [string]); Write-Output ('HI' -is [string])",
            "Write-Output ([char]65 -eq 'A'); Write-Output ('A' -eq 'A')",
            "Write-Output ([char]65 -is [char]); Write-Output ('A' -is [char])",
            '[int]$q = 5; Write-Output $q.ToString()',
            "[int]'42' + 1",
            "[string]$q = 'abc'; Write-Output $q.Substring(1, 1)",
            'function f { $null; 1; $null }; $t = f; Write-Output $t.Count; Write-Output (,$t)',
            'function f { ,$args }; $t = f 1 2; Write-Output (,$t); Write-Output $t.Count',
            'function g { ,(1, 2) }; $t = @(g); Write-Output $t.Count; Write-Output (,$t[0])',
        ),
    ),
    'Ps1DeadCodeElimination': Contribution(
        lost=(
            "Write-Host 'a'; return; Write-Host 'b'",
            "function Raise { throw 'e' }; function Wrap { trap { continue }; Raise; Write-Host 'in' }; Wrap; Write-Host 'after'",
            "function f { try { 'tail' } catch {} }; Write-Host (f)",
            "throw 'e'; Write-Host 'after'",
            'trap [E] { 1 }',
            "trap { continue }; 1/0; Write-Host 'after'",
            "trap { continue }; [int]'a'; Write-Host 'after'",
            "trap { continue }; zzq0000=5; Write-Host 'after'",
            "trap { }; [int]'a'; Write-Host 'after'",
            "try { throw 'x' } catch { 'caught' }",
            "try { zzqq0 =5 } catch {}; Write-Host 'after'",
        ),
        changed=(
            'do { 1 } while ($a)',
            'for ($i = 0; $i -lt 2; $i++) { 1 }',
            'if ($a) { 1 }',
            'if ($a) { 1 } elseif ($b) { 2 } else { 3 }',
            "if ($true) { 'yes' } else { 'no' }",
            "switch ('b') { 'a' { 'first' } 'b' { 'second' } }",
            "trap { continue }; iex 'throw 1'; Write-Host 'after'",
            "try { zzq0000=5 } catch {}; 'next'",
            "try { zzq0000=5; 'tail' } catch {}; 'next'",
            'while ($a) { 1 }',
            'while ($a) { break }',
            'while ($a) { continue }',
        ),
    ),
    'Ps1ControlFlowDeflattening': Contribution(
        lost=(),
        changed=(),
    ),
    'Ps1ConstantInlining': Contribution(
        lost=(
            '$a = 1; $b = 2; $a + $b',
            "$a = @(0); $t = if ($a) { 'yes' } else { 'no' }; Write-Output (,$t); Write-Output $t",
            "$a = @(0, 0); $t = if ($a) { 'yes' } else { 'no' }; Write-Output (,$t); Write-Output $t",
            "$c = 'Write-Out'; $c += 'put 5'; Invoke-Expression $c",
            '$c = [char]65; $s = \'A\'; Write-Output "$c"; Write-Output "$s"',
            '$c = [char]65; foreach ($e in $c) { Write-Output $e }',
            "$env:z = 'v'; Write-Output $env:z",
            "$m = 'Reverse'; $x = 1, 2, 3; [Array]::$m($x); Write-Output $x[0]",
            "$n = 'zq2'; Set-Alias zq2 Write-Host; Set-Alias $n Write-Output; zq2 'y'",
            '$n = 1; $n += 2; Write-Output $n',
            '$n = 1; $n++; Write-Output $n',
            '$n = 5; $n -= 2; Write-Output $n',
            '$p = @(@(1, 2), @(3, 4)); $p | ForEach-Object { [Array]::Reverse($_) }; Write-Output $p[0]',
            '$p = @(@(1, 2), @(3, 4)); $q = $p[0]; $q[0] = 9; Write-Output $p[0][0]',
            '$p = @(@(1, 2), @(3, 4)); foreach ($e in $p) { [Array]::Reverse($e) }; Write-Output $p[0]',
            "$q = 'a'; Write-Output $($q + 'b')",
            "$q = 'abc'; [int]$q = 5; Write-Output $q.GetType().FullName",
            "$s = 'a'; $s += 'b'; $s += 'c'; Write-Output $s",
            "$s = 'abc'; $s.Substring(1, 2)",
            '$s = 0xFF; $t = "$s"; Write-Output (,$t); Write-Output $t',
            '$sb = { param($a) [Array]::Reverse($a) }; $x = 1, 2, 3; & $sb $x; Write-Output $x',
            "$script:s = 'x'; Write-Output $s",
            "$t = 'a', 1; Write-Output (,$t); Write-Output $t",
            '$t = (1, 2), 3; Write-Output (,$t); Write-Output $t.Count',
            '$t = , 1; Write-Output (,$t); Write-Output $t.Count',
            '$t = ,(1, 2); Write-Output (,$t); Write-Output $t.Count',
            '$t = -0.0; Write-Output (,$t); Write-Output $t',
            '$t = -2147483648; Write-Output (,$t); Write-Output $t',
            '$t = -2147483649; Write-Output (,$t); Write-Output $t',
            '$t = -79228162514264337593543950335d; Write-Output (,$t); Write-Output $t',
            '$t = 007; Write-Output (,$t); Write-Output $t',
            '$t = 0x0000000000000001; Write-Output (,$t); Write-Output $t',
            '$t = 0x100000000; Write-Output (,$t); Write-Output $t',
            '$t = 0x7FFFFFFF; Write-Output (,$t); Write-Output $t',
            '$t = 0x7FFFFFFFFFFFFFFF; Write-Output (,$t); Write-Output $t',
            '$t = 0xFF; Write-Output (,$t); Write-Output $t',
            '$t = 0xFFFFFFFF; Write-Output (,$t); Write-Output $t',
            '$t = 0xFFFFFFFFFFFFFFFF; Write-Output (,$t); Write-Output $t',
            '$t = 0xFFFFFFFFL; Write-Output (,$t); Write-Output $t',
            '$t = 0xFFL; Write-Output (,$t); Write-Output $t',
            '$t = 0xFFkb; Write-Output (,$t); Write-Output $t',
            '$t = 1.0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.10d; Write-Output (,$t); Write-Output $t',
            '$t = 1.2345678901234567890123456789d; Write-Output (,$t); Write-Output $t',
            '$t = 1.5; Write-Output (,$t); Write-Output $t',
            '$t = 1.5L; Write-Output (,$t); Write-Output $t',
            '$t = 1.5d; Write-Output (,$t); Write-Output $t',
            '$t = 1.5kb; Write-Output (,$t); Write-Output $t',
            '$t = 100000000000000000000000000000000; Write-Output (,$t); Write-Output $t',
            '$t = 10000000000000000000000000000d; Write-Output (,$t); Write-Output $t',
            '$t = 10D; Write-Output (,$t); Write-Output $t',
            '$t = 10d; Write-Output (,$t); Write-Output $t',
            '$t = 1E+28d; Write-Output (,$t); Write-Output $t',
            '$t = 1L; Write-Output (,$t); Write-Output $t',
            '$t = 1dkb; Write-Output (,$t); Write-Output $t',
            '$t = 1e3; Write-Output (,$t); Write-Output $t',
            '$t = 1kb; Write-Output (,$t); Write-Output $t',
            '$t = 1l; Write-Output (,$t); Write-Output $t',
            '$t = 1lkb; Write-Output (,$t); Write-Output $t',
            '$t = 2.5L; Write-Output (,$t); Write-Output $t',
            '$t = 2147483648; Write-Output (,$t); Write-Output $t',
            '$t = 4gb; Write-Output (,$t); Write-Output $t',
            '$t = 7922816251426433759354395033.5d; Write-Output (,$t); Write-Output $t',
            '$t = 79228162514264337593543950335d; Write-Output (,$t); Write-Output $t',
            '$t = 9223372036854775807; Write-Output (,$t); Write-Output $t',
            '$t = 9223372036854775808; Write-Output (,$t); Write-Output $t',
            '$t = @((1, 2)); Write-Output (,$t); Write-Output $t.Count',
            '$t = @(); Write-Output (,$t); Write-Output $t.Count',
            '$t = @(@(1, 2)); Write-Output (,$t); Write-Output $t.Count',
            '$t = @(@(1, 2), 3); Write-Output (,$t); Write-Output $t.Count',
            '$t = [byte]5; Write-Output (,$t); Write-Output $t',
            "$t = [char[]]'ABC'; Write-Output (,$t); Write-Output $t.Count",
            '$t = [char[]](72, 73); Write-Output (,$t); Write-Output $t',
            '$t = [char]0; Write-Output (,$t); Write-Output $t',
            '$t = [char]65535; Write-Output (,$t); Write-Output $t',
            '$t = [char]65; Write-Output (,$t); Write-Output $t',
            '$t = [int16]7; Write-Output (,$t); Write-Output $t',
            '$t = [sbyte]-5; Write-Output (,$t); Write-Output $t',
            '$t = [uint16]7; Write-Output (,$t); Write-Output $t',
            '$t = [uint32]7; Write-Output (,$t); Write-Output $t',
            '$t = [uint64]18446744073709551615; Write-Output (,$t); Write-Output $t',
            '$t = [uint64]7; Write-Output (,$t); Write-Output $t',
            '$v = 41; & { $v++; Write-Host $v }; Write-Host $v',
            '$x = 1, 2, 3; $a = 0, 0; $a[0] = $x; $a[0][0] = 9; Write-Output $x',
            '$x = 1, 2, 3; $a = 0, 0; $a[0] = $x; Write-Output $a[0]',
            '$x = 1, 2, 3; $a, $b = $x, 9; $a[0] = 7; Write-Output $x[0]',
            '$x = 1, 2, 3; $a, $b = $x, 9; Write-Output $a',
            '$x = 1, 2, 3; $a, $b = $x, 9; [Array]::Reverse($a); Write-Output $x',
            '$x = 1, 2, 3; $h = @{ k = $x }; $h.k[0] = 9; Write-Output $x',
            "$x = 1, 2, 3; $h = @{ k = $x }; $y = $h['k']; $y[0] = 9; Write-Output $x",
            '$x = 1, 2, 3; $h = @{ k = $x }; Write-Output $h.k',
            "$x = 1, 2, 3; $h = @{}; $h['k'] = $x; Write-Output $h['k']",
            "$x = 1, 2, 3; $h = @{}; $h['k'] = $x; [Array]::Reverse($h['k']); Write-Output $x",
            '$x = 1, 2, 3; $l = New-Object Collections.ArrayList; [void]$l.Add($x); $l[0][0] = 9; Write-Output $x',
            '$x = 1, 2, 3; $o = [pscustomobject]@{ P = 0 }; $o.P = $x; $o.P[0] = 9; Write-Output $x',
            '$x = 1, 2, 3; $o = [pscustomobject]@{ P = 0 }; $o.P = $x; Write-Output $o.P',
            '$x = 1, 2, 3; $y = $x; & { $y = 9, 9, 9 }; [Array]::Reverse($x); Write-Output $y',
            '$x = 1, 2, 3; $y = $x; Write-Output $y[0]; [Array]::Reverse($x); Write-Output $y[0]',
            '$x = 1, 2, 3; $y = 0, 0, 0; $x.CopyTo($y, 0); Write-Output $y',
            '$x = 1, 2, 3; $y = 0, 0, 0; [Array]::Copy($x, $y, 3); Write-Output $y',
            '$x = 1, 2, 3; $y = if ($True) { $x }; $x[0] = 9; Write-Output $y[0]',
            '$x = 1, 2, 3; Write-Output $x[0]; $x[0] = 9; Write-Output $x[0]',
            '$x = 1, 2, 3; Write-Output $x[0]; [Array]::Reverse($x); Write-Output $x[0]',
            '$x = 1, 2, 3; [Array]::Clear($x, 0, 1); Write-Output $x',
            '$x = 1, 2, 3; [Array]::Reverse($script:x); Write-Output $x',
            '$x = 1, 2, 3; [Array]::Reverse($x, 0, 2); Write-Output $x',
            '$x = 1, 2, 3; [Array]::Reverse(($x)); Write-Output $x',
            "$x = @('a', 'b'); $x[1]",
            '$z = 1.100d; $t = $z + 0d; Write-Output (,$t); Write-Output $t',
            '$z = 1.50d; $t = $z + 1.50d; Write-Output (,$t); Write-Output $t',
            "Set-Alias zzq Write-Host; $c = 'Set-Alias'; & $c zzq Write-Output; zzq 'x'",
            "Set-Alias zzq Write-Output; $n = 'zzq'; & $n 'dispatched'",
            "Set-Alias zzq Write-Output; $n = 'zzq'; (Get-Alias $n).Definition",
            "Write-Output $($w = 'x'; $w); Write-Output $w",
            '[int]$q = 5; Write-Output $q.ToString()',
            "[string]$q = 'abc'; Write-Output $q.Substring(1, 1)",
            "[string]$q = 5; $q += 'a'; Write-Output (,$q)",
            "[string]$q = 5; [System.String]$q = 'ab'; Write-Output $q",
            'function f($a) { $script:k = $a }; $x = 1, 2, 3; f $x; $x[0] = 9; Write-Output $k[0]',
            'function f($a) { [Array]::Reverse($a) }; $x = 1, 2, 3; f $x; Write-Output $x',
        ),
        changed=(
            "$OFS = '-'; $t = [string]('a', 'b'); Write-Output $t",
            '$a = $null; $b = 5; $t = $a * $b; Write-Output (,$t)',
            '$a = $null; $t = $a * 5; Write-Output (,$t)',
            "$c = 'Write-Output $w'; $x = $($w = 'a'; 'v'); iex $c",
            "$env:B = 'function K { Write-Host P }'; Invoke-Expression $env:B; function K { 42 }; $x = K; Write-Output $x; $env:C = 'K'; Invoke-Expression $env:C",
            "$env:z = '7'; $ok = [int]::TryParse('42', [ref]$env:z); Write-Host $env:z",
            '$l = [byte]1; $r = 4; $t = $l -shl $r; Write-Output (,$t); Write-Output $t',
            "$n = 'q'; function K { $Null = 1 }; Set-Alias $n K; q; Write-Host 'A'",
            '$q = [string]5; $q = 1, 2, 3; Write-Output (,$q)',
            "$s = 'abcd'; $t = $s; $t = 1, 2, 3; [Array]::Reverse($t); Write-Output $s.Length",
            '$t = $false + 1; Write-Output (,$t); Write-Output $t',
            '$t = $false -eq $null; Write-Output (,$t); Write-Output $t',
            '$t = $false -eq 0; Write-Output (,$t); Write-Output $t',
            '$t = $false -gt $null; Write-Output (,$t); Write-Output $t',
            '$t = $false -lt 5; Write-Output (,$t); Write-Output $t',
            '$t = $null * 1; Write-Output (,$t)',
            '$t = $null + $true; Write-Output (,$t); Write-Output $t',
            "$t = $null + 'abc'; Write-Output (,$t); Write-Output $t",
            '$t = $null + 1.5d; Write-Output (,$t); Write-Output $t',
            '$t = $null + 5; Write-Output (,$t); Write-Output $t',
            '$t = $null + @(1, 2); Write-Output (,$t); Write-Output $t.Count',
            '$t = $null + [char]65; Write-Output (,$t); Write-Output $t',
            '$t = $null - 5; Write-Output (,$t); Write-Output $t',
            '$t = $null -band 1; Write-Output (,$t); Write-Output $t',
            '$t = $null -eq $false; Write-Output (,$t); Write-Output $t',
            '$t = $null -eq $null; Write-Output (,$t); Write-Output $t',
            "$t = $null -eq ''; Write-Output (,$t); Write-Output $t",
            '$t = $null -eq 0; Write-Output (,$t); Write-Output $t',
            '$t = $null -ge 1; Write-Output (,$t); Write-Output $t',
            '$t = $null -gt -5; Write-Output (,$t); Write-Output $t',
            '$t = $null -gt 1; Write-Output (,$t); Write-Output $t',
            '$t = $null -le -5; Write-Output (,$t); Write-Output $t',
            '$t = $null -le 1; Write-Output (,$t); Write-Output $t',
            "$t = $null -lt ''; Write-Output (,$t); Write-Output $t",
            "$t = $null -lt 'abc'; Write-Output (,$t); Write-Output $t",
            '$t = $null -lt -5; Write-Output (,$t); Write-Output $t',
            '$t = $null -lt 0; Write-Output (,$t); Write-Output $t',
            '$t = $null -lt 1; Write-Output (,$t); Write-Output $t',
            '$t = $null -ne $null; Write-Output (,$t); Write-Output $t',
            '$t = $null -ne 0; Write-Output (,$t); Write-Output $t',
            '$t = $null -or $false; Write-Output (,$t); Write-Output $t',
            '$t = $null.Count; Write-Output (,$t); Write-Output $t',
            '$t = $true * 1.5d; Write-Output (,$t); Write-Output $t',
            '$t = $true + $true; Write-Output (,$t); Write-Output $t',
            "$t = $true + ''; Write-Output (,$t); Write-Output $t",
            '$t = $true + 1.5; Write-Output (,$t); Write-Output $t',
            '$t = $true + 1; Write-Output (,$t); Write-Output $t',
            '$t = $true + 9223372036854775807L; Write-Output (,$t); Write-Output $t',
            '$t = $true - 1.5; Write-Output (,$t); Write-Output $t',
            '$t = $true - 1; Write-Output (,$t); Write-Output $t',
            '$t = $true -and $true; Write-Output (,$t); Write-Output $t',
            "$t = $true -and ''; Write-Output (,$t); Write-Output $t",
            '$t = $true -and @(); Write-Output (,$t); Write-Output $t',
            '$t = $true -and [char]0; Write-Output (,$t); Write-Output $t',
            '$t = $true -band 1; Write-Output (,$t); Write-Output $t',
            '$t = $true -bxor $false; Write-Output (,$t); Write-Output $t',
            '$t = $true -eq $null; Write-Output (,$t); Write-Output $t',
            "$t = $true -eq ''; Write-Output (,$t); Write-Output $t",
            "$t = $true -eq '0'; Write-Output (,$t); Write-Output $t",
            "$t = $true -eq 'abc'; Write-Output (,$t); Write-Output $t",
            '$t = $true -eq 1; Write-Output (,$t); Write-Output $t',
            '$t = $true -eq 2; Write-Output (,$t); Write-Output $t',
            "$t = $true -ge 'abc'; Write-Output (,$t); Write-Output $t",
            '$t = $true -gt $false; Write-Output (,$t); Write-Output $t',
            '$t = $true -gt 2; Write-Output (,$t); Write-Output $t',
            '$t = $true -lt 2; Write-Output (,$t); Write-Output $t',
            '$t = $true -ne 2; Write-Output (,$t); Write-Output $t',
            '$t = $true -xor $true; Write-Output (,$t); Write-Output $t',
            '$t = $true / 1; Write-Output (,$t); Write-Output $t',
            "$t = ' ' -and $true; Write-Output (,$t); Write-Output $t",
            "$t = '' -eq $null; Write-Output (,$t); Write-Output $t",
            "$t = '' -eq '0'; Write-Output (,$t); Write-Output $t",
            "$t = '' -eq 0; Write-Output (,$t); Write-Output $t",
            "$t = '' -gt $null; Write-Output (,$t); Write-Output $t",
            "$t = '' -or $false; Write-Output (,$t); Write-Output $t",
            "$t = '0' -and $true; Write-Output (,$t); Write-Output $t",
            "$t = '0' -eq 0; Write-Output (,$t); Write-Output $t",
            "$t = '1.0' -eq 1; Write-Output (,$t); Write-Output $t",
            "$t = '10' -band 6; Write-Output (,$t); Write-Output $t",
            "$t = '10' -ne 10; Write-Output (,$t); Write-Output $t",
            "$t = '1000' -eq 1e3d; Write-Output (,$t); Write-Output $t",
            "$t = '1e400' + 1; Write-Output (,$t); Write-Output $t",
            "$t = '5' * 2; Write-Output (,$t); Write-Output $t",
            "$t = '5' + 5; Write-Output (,$t); Write-Output $t",
            "$t = '5' - 1; Write-Output (,$t); Write-Output $t",
            "$t = '5' / 2; Write-Output (,$t); Write-Output $t",
            "$t = 'A' -ceq 'a'; Write-Output (,$t); Write-Output $t",
            "$t = 'A' -ieq 'a'; Write-Output (,$t); Write-Output $t",
            "$t = 'AB'.Count; Write-Output (,$t); Write-Output $t",
            "$t = 'AB'.Length; Write-Output (,$t); Write-Output $t",
            "$t = 'AB'.Zqnope; Write-Output (,$t)",
            "$t = 'ABC'[0]; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + $false; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + $null; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + $true; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + -1.50d; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + 0.5d; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + 1.50d; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + 1.5; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + 1L; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + 1e3d; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + 79228162514264337593543950335d; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + [char]65; Write-Output (,$t); Write-Output $t",
            "$t = 'a' + [uint64]18446744073709551615; Write-Output (,$t); Write-Output $t",
            "$t = 'a-b-c' -split '-' | ForEach-Object { $_ }; Write-Output (,$t)",
            "$t = 'abc' -and $true; Write-Output (,$t); Write-Output $t",
            "$t = 'abc' -eq $true; Write-Output (,$t); Write-Output $t",
            "$t = 'abc' -lt $null; Write-Output (,$t); Write-Output $t",
            "$t = 'abc' -replace '(?<x>b)', '[${x}]'; Write-Output (,$t); Write-Output $t",
            "$t = 'false' -and $true; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + (1.0d); Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 0.0d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 1.000d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 1.00d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 1.0d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 1.100d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 1.10d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 1.2300d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 10.0d; Write-Output (,$t); Write-Output $t",
            "$t = 'x' + 2.0d; Write-Output (,$t); Write-Output $t",
            "$t = ('A').Substring(0); Write-Output (,$t); Write-Output $t",
            "$t = ('A').ToUpper(); Write-Output (,$t); Write-Output $t",
            '$t = (,$true) -and $true; Write-Output (,$t); Write-Output $t',
            "$t = (,' ') -and $true; Write-Output (,$t); Write-Output $t",
            "$t = (,'') -and $true; Write-Output (,$t); Write-Output $t",
            "$t = (,'a') -and $true; Write-Output (,$t); Write-Output $t",
            '$t = (,(,(,0))) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,(,0)) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,(,@())) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,0.0) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,0.0d) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,1) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,@()) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,@(1, 2)) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,[char]0) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = (,[char]65) -and $true; Write-Output (,$t); Write-Output $t',
            "$t = (- '0') -and $true; Write-Output (,$t); Write-Output $t",
            '$t = (5).Count; Write-Output (,$t); Write-Output $t',
            '$t = (5).Length; Write-Output (,$t); Write-Output $t',
            '$t = (5).Rank; Write-Output (,$t)',
            '$t = (5).Zqnope; Write-Output (,$t)',
            '$t = ([char]65).ToString(); Write-Output (,$t); Write-Output $t',
            '$t = - $false; Write-Output (,$t); Write-Output $t',
            '$t = - $null; Write-Output (,$t); Write-Output $t',
            '$t = - $true; Write-Output (,$t); Write-Output $t',
            "$t = - ' 5 '; Write-Output (,$t); Write-Output $t",
            "$t = - ''; Write-Output (,$t); Write-Output $t",
            "$t = - '0'; Write-Output (,$t); Write-Output $t",
            "$t = - '1e3'; Write-Output (,$t); Write-Output $t",
            "$t = - '5'; Write-Output (,$t); Write-Output $t",
            '$t = - (-2147483648); Write-Output (,$t); Write-Output $t',
            '$t = - 0.0; Write-Output (,$t); Write-Output $t',
            '$t = - 0.0d; Write-Output (,$t); Write-Output $t',
            '$t = - 0; Write-Output (,$t); Write-Output $t',
            '$t = - 0d; Write-Output (,$t); Write-Output $t',
            '$t = - 1.00d; Write-Output (,$t); Write-Output $t',
            '$t = - 1.0d; Write-Output (,$t); Write-Output $t',
            '$t = - 1.10d; Write-Output (,$t); Write-Output $t',
            '$t = - 1.5; Write-Output (,$t); Write-Output $t',
            '$t = - 1.5d; Write-Output (,$t); Write-Output $t',
            '$t = - 2147483647; Write-Output (,$t); Write-Output $t',
            '$t = - 2147483648; Write-Output (,$t); Write-Output $t',
            '$t = - 5; Write-Output (,$t); Write-Output $t',
            '$t = - 79228162514264337593543950335d; Write-Output (,$t); Write-Output $t',
            '$t = - 9223372036854775807L; Write-Output (,$t); Write-Output $t',
            '$t = - [byte]5; Write-Output (,$t); Write-Output $t',
            '$t = - [char]0; Write-Output (,$t); Write-Output $t',
            '$t = - [char]65; Write-Output (,$t); Write-Output $t',
            '$t = - [uint32]1; Write-Output (,$t); Write-Output $t',
            '$t = - [uint64]18446744073709551615; Write-Output (,$t); Write-Output $t',
            '$t = -(2147483647); Write-Output (,$t); Write-Output $t',
            '$t = -(2147483648); Write-Output (,$t); Write-Output $t',
            '$t = -0.0 -or $false; Write-Output (,$t); Write-Output $t',
            '$t = -1 * [uint64]1; Write-Output (,$t); Write-Output $t',
            '$t = -1 -band [uint32]1; Write-Output (,$t); Write-Output $t',
            '$t = -2147483647 - 1; Write-Output (,$t); Write-Output $t',
            '$t = -2147483648 % -1; Write-Output (,$t); Write-Output $t',
            '$t = -2147483648 - 9223372036854775807L; Write-Output (,$t); Write-Output $t',
            '$t = -2147483648 / -1; Write-Output (,$t); Write-Output $t',
            '$t = -bnot $null; Write-Output (,$t); Write-Output $t',
            '$t = -bnot $true; Write-Output (,$t); Write-Output $t',
            "$t = -bnot '5'; Write-Output (,$t); Write-Output $t",
            '$t = -bnot 0xFF; Write-Output (,$t); Write-Output $t',
            '$t = -bnot 0xFFFFFFFF; Write-Output (,$t); Write-Output $t',
            '$t = -bnot 1.5; Write-Output (,$t); Write-Output $t',
            '$t = -bnot 10d; Write-Output (,$t); Write-Output $t',
            '$t = -bnot 1L; Write-Output (,$t); Write-Output $t',
            '$t = -bnot [byte]5; Write-Output (,$t); Write-Output $t',
            '$t = -bnot [char]65; Write-Output (,$t); Write-Output $t',
            '$t = -bnot [uint32]7; Write-Output (,$t); Write-Output $t',
            "$t = -not '0'; Write-Output (,$t); Write-Output $t",
            '$t = -not (,[char]0); Write-Output (,$t); Write-Output $t',
            "$t = -not (- '0'); Write-Output (,$t); Write-Output $t",
            '$t = -not @(); Write-Output (,$t); Write-Output $t',
            '$t = -not @(0); Write-Output (,$t); Write-Output $t',
            '$t = -not [char]0; Write-Output (,$t); Write-Output $t',
            "$t = 0 + '5'; Write-Output (,$t); Write-Output $t",
            '$t = 0 + [char]65; Write-Output (,$t); Write-Output $t',
            '$t = 0 - [uint64]18446744073709551615; Write-Output (,$t); Write-Output $t',
            '$t = 0 -eq $null; Write-Output (,$t); Write-Output $t',
            "$t = 0 -eq '0'; Write-Output (,$t); Write-Output $t",
            '$t = 0 -gt $null; Write-Output (,$t); Write-Output $t',
            '$t = 0 -or 0; Write-Output (,$t); Write-Output $t',
            '$t = 0.0 -or $false; Write-Output (,$t); Write-Output $t',
            '$t = 0.0d -or $false; Write-Output (,$t); Write-Output $t',
            '$t = 0L -or $false; Write-Output (,$t); Write-Output $t',
            '$t = 0xFFFFFFFF + 0; Write-Output (,$t); Write-Output $t',
            '$t = 0xFFFFFFFF -bxor 0x5A; Write-Output (,$t); Write-Output $t',
            '$t = 0xFFFFFFFFFFFFFFFF + 0; Write-Output (,$t); Write-Output $t',
            '$t = 1 + $true; Write-Output (,$t); Write-Output $t',
            "$t = 1 + '  '; Write-Output (,$t); Write-Output $t",
            "$t = 1 + ' 7 '; Write-Output (,$t); Write-Output $t",
            "$t = 1 + '+5'; Write-Output (,$t); Write-Output $t",
            "$t = 1 + '0xFFFFFFFF'; Write-Output (,$t); Write-Output $t",
            "$t = 1 + '1.5L'; Write-Output (,$t); Write-Output $t",
            "$t = 1 + '1e3'; Write-Output (,$t); Write-Output $t",
            "$t = 1 + '1kb'; Write-Output (,$t); Write-Output $t",
            "$t = 1 + '2147483648'; Write-Output (,$t); Write-Output $t",
            "$t = 1 + '5'; Write-Output (,$t); Write-Output $t",
            "$t = 1 + 'AB'.Count; Write-Output (,$t); Write-Output $t",
            '$t = 1 + [uint64]18446744073709551615; Write-Output (,$t); Write-Output $t',
            '$t = 1 - $true; Write-Output (,$t); Write-Output $t',
            "$t = 1 - '5'; Write-Output (,$t); Write-Output $t",
            '$t = 1 -and 0; Write-Output (,$t); Write-Output $t',
            '$t = 1 -and 2; Write-Output (,$t); Write-Output $t',
            '$t = 1 -ceq 1; Write-Output (,$t); Write-Output $t',
            "$t = 1 -eq '1.0'; Write-Output (,$t); Write-Output $t",
            '$t = 1 -ge $null; Write-Output (,$t); Write-Output $t',
            '$t = 1 -gt $null; Write-Output (,$t); Write-Output $t',
            '$t = 1 -le $null; Write-Output (,$t); Write-Output $t',
            '$t = 1 -lt $null; Write-Output (,$t); Write-Output $t',
            '$t = 1 -ne $null; Write-Output (,$t); Write-Output $t',
            '$t = 1 / [uint64]18446744073709551615; Write-Output (,$t); Write-Output $t',
            '$t = 1.000d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.00d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.0d * 1d; Write-Output (,$t); Write-Output $t',
            '$t = 1.0d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.0d + 2.0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.0d - $true; Write-Output (,$t); Write-Output $t',
            '$t = 1.0d - 0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.0d / 1d; Write-Output (,$t); Write-Output $t',
            '$t = 1.100d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.10d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.2345678901234567890123456789d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 1.5 * [char]48; Write-Output (,$t); Write-Output $t',
            '$t = 1.500d + 1.500d; Write-Output (,$t); Write-Output $t',
            '$t = 1.50d + 1.50d; Write-Output (,$t); Write-Output $t',
            '$t = 1.5d -and $true; Write-Output (,$t); Write-Output $t',
            '$t = 10 - $null + 3; Write-Output (,$t); Write-Output $t',
            '$t = 10 - $null; Write-Output (,$t); Write-Output $t',
            "$t = 10 -ne '10'; Write-Output (,$t); Write-Output $t",
            '$t = 10 -ne 20; Write-Output (,$t); Write-Output $t',
            '$t = 10, 20, 30 -eq 20; Write-Output (,$t); Write-Output $t',
            '$t = 10, 20, 30, 20, 10 -ne 20; Write-Output (,$t); Write-Output $t',
            '$t = 100000000000000d * 100000000000000d; Write-Output (,$t); Write-Output $t',
            '$t = 10d + 0; Write-Output (,$t); Write-Output $t',
            "$t = 12 + '0xabc'; Write-Output (,$t); Write-Output $t",
            '$t = 1L + 0; Write-Output (,$t); Write-Output $t',
            '$t = 1L -shl 64; Write-Output (,$t); Write-Output $t',
            '$t = 1d / 3d; Write-Output (,$t); Write-Output $t',
            '$t = 1kb + 0; Write-Output (,$t); Write-Output $t',
            '$t = 2 * $true; Write-Output (,$t); Write-Output $t',
            '$t = 2 * [char]48; Write-Output (,$t); Write-Output $t',
            '$t = 2 -eq $true; Write-Output (,$t); Write-Output $t',
            '$t = 2.50d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 2147483647 * 2147483647; Write-Output (,$t); Write-Output $t',
            '$t = 2147483647 * [uint32]4294967295; Write-Output (,$t); Write-Output $t',
            '$t = 2147483647 + 1; Write-Output (,$t); Write-Output $t',
            "$t = 5 + '5'; Write-Output (,$t); Write-Output $t",
            '$t = 5 -as [long]; Write-Output (,$t); Write-Output $t',
            '$t = 5 -xor 0; Write-Output (,$t); Write-Output $t',
            '$t = 512MB * 512MB; Write-Output (,$t); Write-Output $t',
            '$t = 65, 66 | ForEach-Object { [char]$_ }; Write-Output $t.Count; Write-Output $t',
            '$t = 65, 66 | ForEach-Object { [char]$_ }; Write-Output (,$t)',
            '$t = 79228162514264337593543950334d + 1d; Write-Output (,$t); Write-Output $t',
            '$t = 79228162514264337593543950335d * 1d; Write-Output (,$t); Write-Output $t',
            '$t = 79228162514264337593543950335d + 0d; Write-Output (,$t); Write-Output $t',
            '$t = 79228162514264337593543950335d - 1d; Write-Output (,$t); Write-Output $t',
            '$t = 79228162514264337593543950335d / 1d; Write-Output (,$t); Write-Output $t',
            '$t = 9223372036854775807 + 2; Write-Output (,$t); Write-Output $t',
            '$t = 9223372036854775807L + 1; Write-Output (,$t); Write-Output $t',
            '$t = 9223372036854775807L - -1L; Write-Output (,$t); Write-Output $t',
            '$t = @($false) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = @($null) -and $true; Write-Output (,$t); Write-Output $t',
            "$t = @('a', 'b') | ForEach-Object { $_ }; Write-Output ($t -join '-')",
            "$t = @('a', 'b') | ForEach-Object { $_ }; Write-Output (,$t); Write-Output $t",
            "$t = @('a', 'b') | ForEach-Object { $_ }; foreach ($e in $t) { Write-Output $e }",
            '$t = @() * 5000; Write-Output (,$t); Write-Output $t.Count',
            '$t = @() + 1; Write-Output (,$t); Write-Output $t.Count',
            '$t = @() -or $false; Write-Output (,$t); Write-Output $t',
            '$t = @(0) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = @(0, 0) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = @(1, 2) * 0; Write-Output (,$t); Write-Output $t.Count',
            '$t = @(1, 2) * 2; Write-Output (,$t); Write-Output $t.Count',
            '$t = @(1, 2) + $null; Write-Output (,$t); Write-Output $t.Count',
            "$t = @(1, 2) + 'a'; Write-Output (,$t); Write-Output $t.Count",
            '$t = @(1, 2) + 5; Write-Output (,$t); Write-Output $t.Count',
            '$t = @(1, 2) + @(3, 4); Write-Output (,$t); Write-Output $t.Count',
            '$t = @(1, 2) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = @(1, 2) -eq $null; Write-Output (,$t); Write-Output $t',
            '$t = @(1, 2, 3) -and $true; Write-Output (,$t); Write-Output $t',
            '$t = @(1, 2, 3).Count; Write-Output (,$t); Write-Output $t',
            '$t = @(1, 2, 3).Length; Write-Output (,$t); Write-Output $t',
            '$t = @(1, 2, 3).Rank; Write-Output (,$t); Write-Output $t',
            '$t = @(@()) -and $true; Write-Output (,$t); Write-Output $t',
            "$t = [Convert]::ToByte('FF', 16); Write-Output (,$t); Write-Output $t",
            '$t = [Convert]::ToChar(65); Write-Output (,$t); Write-Output $t',
            '$t = [Convert]::ToInt32($null); Write-Output (,$t); Write-Output $t',
            "$t = [Convert]::ToInt32(' 5 '); Write-Output (,$t); Write-Output $t",
            "$t = [Convert]::ToInt32('017', 8); Write-Output (,$t); Write-Output $t",
            "$t = [Convert]::ToInt32('80000000', 16); Write-Output (,$t); Write-Output $t",
            "$t = [Convert]::ToInt32('FFFFFFFF', 16); Write-Output (,$t); Write-Output $t",
            '$t = [Convert]::ToInt32(1.5); Write-Output (,$t); Write-Output $t',
            '$t = [Convert]::ToInt32(1.5d); Write-Output (,$t); Write-Output $t',
            '$t = [Convert]::ToInt64(5); Write-Output (,$t); Write-Output $t',
            '$t = [bool]$null; Write-Output (,$t); Write-Output $t',
            "$t = [bool]' '; Write-Output (,$t); Write-Output $t",
            "$t = [bool]''; Write-Output (,$t); Write-Output $t",
            "$t = [bool]'0'; Write-Output (,$t); Write-Output $t",
            "$t = [bool]'a'; Write-Output (,$t); Write-Output $t",
            "$t = [bool]'false'; Write-Output (,$t); Write-Output $t",
            '$t = [bool](,$null); Write-Output (,$t); Write-Output $t',
            '$t = [bool](,(,0)); Write-Output (,$t); Write-Output $t',
            '$t = [bool](,1); Write-Output (,$t); Write-Output $t',
            '$t = [bool](,@()); Write-Output (,$t); Write-Output $t',
            '$t = [bool](,@(1, 2)); Write-Output (,$t); Write-Output $t',
            '$t = [bool](,[char]0); Write-Output (,$t); Write-Output $t',
            '$t = [bool]-0.0; Write-Output (,$t); Write-Output $t',
            '$t = [bool]0.0; Write-Output (,$t); Write-Output $t',
            '$t = [bool]0.0d; Write-Output (,$t); Write-Output $t',
            '$t = [bool]0; Write-Output (,$t); Write-Output $t',
            '$t = [bool]1.5d; Write-Output (,$t); Write-Output $t',
            '$t = [bool]1; Write-Output (,$t); Write-Output $t',
            '$t = [bool]@($false); Write-Output (,$t); Write-Output $t',
            '$t = [bool]@($null); Write-Output (,$t); Write-Output $t',
            '$t = [bool]@(); Write-Output (,$t); Write-Output $t',
            '$t = [bool]@(0); Write-Output (,$t); Write-Output $t',
            '$t = [bool]@(0, 0); Write-Output (,$t); Write-Output $t',
            '$t = [bool]@(0, 0, 0); Write-Output (,$t); Write-Output $t',
            '$t = [bool]@(@()); Write-Output (,$t); Write-Output $t',
            "$t = [bool][char]'0'; Write-Output (,$t); Write-Output $t",
            '$t = [bool][char]0; Write-Output (,$t); Write-Output $t',
            '$t = [bool][int16]0; Write-Output (,$t); Write-Output $t',
            '$t = [bool][sbyte]0; Write-Output (,$t); Write-Output $t',
            '$t = [bool][uint16]0; Write-Output (,$t); Write-Output $t',
            '$t = [bool][uint32]0; Write-Output (,$t); Write-Output $t',
            "$t = [byte]'0x80'; Write-Output (,$t); Write-Output $t",
            '$t = [byte]0 -or $false; Write-Output (,$t); Write-Output $t',
            '$t = [char]$null; Write-Output (,$t); Write-Output $t',
            "$t = [char]'0' -and $true; Write-Output (,$t); Write-Output $t",
            "$t = [char]'A'; Write-Output (,$t); Write-Output $t",
            '$t = [char]0 -or $false; Write-Output (,$t); Write-Output $t',
            "$t = [char]48 - '1'; Write-Output (,$t); Write-Output $t",
            '$t = [char]48 - 0.0; Write-Output (,$t); Write-Output $t',
            '$t = [char]48 -band [byte]255; Write-Output (,$t); Write-Output $t',
            '$t = [char]48 -bxor [char]48; Write-Output (,$t); Write-Output $t',
            "$t = [char]48 -eq '0'; Write-Output (,$t); Write-Output $t",
            '$t = [char]48 -eq 48; Write-Output (,$t); Write-Output $t',
            '$t = [char]65 -and $true; Write-Output (,$t); Write-Output $t',
            '$t = [char]65 -bxor 32; Write-Output (,$t); Write-Output $t',
            '$t = [char]65 -ceq [char]97; Write-Output (,$t); Write-Output $t',
            '$t = [char]65 -eq [char]97; Write-Output (,$t); Write-Output $t',
            '$t = [char]65 -lt [char]97; Write-Output (,$t); Write-Output $t',
            '$t = [char]97 -lt [char]66; Write-Output (,$t); Write-Output $t',
            '$t = [decimal]5; Write-Output (,$t); Write-Output $t',
            '$t = [double]1.5d; Write-Output (,$t); Write-Output $t',
            '$t = [double]5; Write-Output (,$t); Write-Output $t',
            '$t = [int]"`t`r5`n"; Write-Output (,$t); Write-Output $t',
            '$t = [int]$null; Write-Output (,$t); Write-Output $t',
            '$t = [int]$true; Write-Output (,$t); Write-Output $t',
            "$t = [int]' 5 '; Write-Output (,$t); Write-Output $t",
            "$t = [int]''; Write-Output (,$t); Write-Output $t",
            "$t = [int]'+7'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'.5'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'0'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'007'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'0x10'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'0xFFFFFFFF'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'2.5'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'5'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'5.'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'7.5'; Write-Output (,$t); Write-Output $t",
            '$t = [int]-1.5; Write-Output (,$t); Write-Output $t',
            '$t = [int]1.4; Write-Output (,$t); Write-Output $t',
            '$t = [int]1.5; Write-Output (,$t); Write-Output $t',
            '$t = [int]10d; Write-Output (,$t); Write-Output $t',
            '$t = [int]2.5; Write-Output (,$t); Write-Output $t',
            '$t = [int]5; Write-Output (,$t); Write-Output $t',
            '$t = [int][char]48; Write-Output (,$t); Write-Output $t',
            '$t = [int][char]65; Write-Output (,$t); Write-Output $t',
            '$t = [long]1.5; Write-Output (,$t); Write-Output $t',
            '$t = [long]5; Write-Output (,$t); Write-Output $t',
            "$t = [sbyte]'0x80'; Write-Output (,$t); Write-Output $t",
            '$t = [string]$false; Write-Output (,$t); Write-Output $t',
            '$t = [string]$null; Write-Output (,$t); Write-Output $t',
            '$t = [string]$true; Write-Output (,$t); Write-Output $t',
            "$t = [string]'foo'; Write-Output (,$t); Write-Output $t",
            "$t = [string]('a', 'b'); Write-Output (,$t); Write-Output $t",
            '$t = [string]-1.50d; Write-Output (,$t); Write-Output $t',
            '$t = [string]0.0000001; Write-Output (,$t); Write-Output $t',
            '$t = [string]0.0d; Write-Output (,$t); Write-Output $t',
            '$t = [string]0.5d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.000d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.00d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.0d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.100d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.10d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.50d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.5; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.5E-7; Write-Output (,$t); Write-Output $t',
            '$t = [string]10d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1E20; Write-Output (,$t); Write-Output $t',
            '$t = [string]1L; Write-Output (,$t); Write-Output $t',
            '$t = [string]2.0d; Write-Output (,$t); Write-Output $t',
            '$t = [string]5; Write-Output (,$t); Write-Output $t',
            '$t = [string]79228162514264337593543950335d; Write-Output (,$t); Write-Output $t',
            '$t = [string][uint64]18446744073709551615; Write-Output (,$t); Write-Output $t',
            "$t = [uint16]'0xFFFF'; Write-Output (,$t); Write-Output $t",
            '$t = [uint64]0 -or $false; Write-Output (,$t); Write-Output $t',
            '$t = [uint64]18446744073709551615 + 1; Write-Output (,$t); Write-Output $t',
            '$v = $null; $t = $v -band [uint32]1; Write-Output (,$t); Write-Output $t',
            '$v = \'a\'; & ([ScriptBlock]::Create(\'$v + "b"\')); Write-Output (1 + 1)',
            '$v = \'a\'; & ([ScriptBlock]::Create(\'$v = "b"\')); Write-Output $v; Write-Output (1 + 1)',
            "$v = 'a'; & { Write-Host $v }; $v = 'c'",
            '$x = $($r = [byte]77; $r); Write-Output ($x -is [byte])',
            '$x = $($r = [char]66; $r); Write-Output ($x -is [char])',
            "$x = $($w = 'a'; 'v'); Write-Output $w",
            "$x = 'a'; $ExecutionContext.InvokeCommand.InvokeScript('Write-Host $x'); $x = 'c'",
            '$x = \'a\'; $c = \'$script:x = "b"\'; function f { iex $c }; f; Write-Host $x',
            "$x = 'a'; $false -and ($x = 'b'); Write-Host $x",
            "$x = 'a'; $true -or ($x = 'b'); Write-Host $x",
            '$x = \'a\'; &(\'i\' + \'ex\') \'$x = "b"\'; Write-Host $x',
            "$x = 'a'; 1..2 | ForEach-Object { Write-Host $x }; $x = 'c'",
            "$x = 'a'; Invoke-Command -ScriptBlock { Write-Host $x }; $x = 'c'",
            "$x = 'hello'; $x",
            "$x = 1, 2, 3; $c = '$x = 7, 8, 9'; iex $c; [Array]::Reverse($x); Write-Output $x",
            '$x = 1, 2, 3; $r = [Array]::Reverse($x); Write-Output $x',
            '$x = 1, 2, 3; $y = $($x); [Array]::Reverse($x); Write-Output $y',
            '$x = 1, 2, 3; $y = $x; $x = 9, 9, 9; Write-Output $y',
            '$x = 1, 2, 3; $y = $x; $y = 9, 9, 9; [Array]::Reverse($x); Write-Output $y',
            "$z = 1.000d; $t = 'x' + $z; Write-Output (,$t); Write-Output $t",
            "$z = 1.00d; $t = 'x' + $z; Write-Output (,$t); Write-Output $t",
            "$z = 1.0d; $t = 'x' + $z; Write-Output (,$t); Write-Output $t",
            "$z = 1.100d; $t = 'x' + $z; Write-Output (,$t); Write-Output $t",
            "$z = 1.10d; $t = 'x' + $z; Write-Output (,$t); Write-Output $t",
            "Set-Variable s 'A'; Write-Output $($s + 'B')",
            'function f { $i = 0; $i++; $i++; $i }; $t = f; Write-Output (,$t); Write-Output $t',
            'function f { $null; 1; $null }; $t = f; Write-Output $t.Count; Write-Output (,$t)',
            "function f { $s = 'abc'; $s++; $s }; $t = f; Write-Output (,$t); Write-Output $t",
            'function f { ,$args }; $t = f 1 2; Write-Output (,$t); Write-Output $t.Count',
            'function g { ,(1, 2) }; $t = @(g); Write-Output $t.Count; Write-Output (,$t[0])',
            'iex \'$u = "U"\'; Write-Output $($u + \'x\')',
        ),
    ),
    'Ps1ExpandableStringHoist': Contribution(
        lost=(),
        changed=(),
    ),
    'Ps1TypeCasts': Contribution(
        lost=(
            "$OFS = '-'; $t = [string]('a', 'b'); Write-Output $t",
            "$t = [bool]' '; Write-Output (,$t); Write-Output $t",
            "$t = [bool]''; Write-Output (,$t); Write-Output $t",
            "$t = [bool]'0'; Write-Output (,$t); Write-Output $t",
            "$t = [bool]'a'; Write-Output (,$t); Write-Output $t",
            "$t = [bool]'false'; Write-Output (,$t); Write-Output $t",
            '$t = [bool](,(,0)); Write-Output (,$t); Write-Output $t',
            '$t = [bool](,1); Write-Output (,$t); Write-Output $t',
            '$t = [bool](,@()); Write-Output (,$t); Write-Output $t',
            '$t = [bool](,@(1, 2)); Write-Output (,$t); Write-Output $t',
            '$t = [bool](,[char]0); Write-Output (,$t); Write-Output $t',
            '$t = [bool]-0.0; Write-Output (,$t); Write-Output $t',
            '$t = [bool]0.0; Write-Output (,$t); Write-Output $t',
            '$t = [bool]0.0d; Write-Output (,$t); Write-Output $t',
            '$t = [bool]0; Write-Output (,$t); Write-Output $t',
            '$t = [bool]1.5d; Write-Output (,$t); Write-Output $t',
            '$t = [bool]1; Write-Output (,$t); Write-Output $t',
            '$t = [bool]@(); Write-Output (,$t); Write-Output $t',
            '$t = [bool]@(0); Write-Output (,$t); Write-Output $t',
            '$t = [bool]@(0, 0); Write-Output (,$t); Write-Output $t',
            '$t = [bool]@(0, 0, 0); Write-Output (,$t); Write-Output $t',
            '$t = [bool]@(@()); Write-Output (,$t); Write-Output $t',
            "$t = [bool][char]'0'; Write-Output (,$t); Write-Output $t",
            '$t = [bool][char]0; Write-Output (,$t); Write-Output $t',
            '$t = [bool][int16]0; Write-Output (,$t); Write-Output $t',
            '$t = [bool][sbyte]0; Write-Output (,$t); Write-Output $t',
            '$t = [bool][uint16]0; Write-Output (,$t); Write-Output $t',
            '$t = [bool][uint32]0; Write-Output (,$t); Write-Output $t',
            '$t = [decimal]5; Write-Output (,$t); Write-Output $t',
            '$t = [double]1.5d; Write-Output (,$t); Write-Output $t',
            '$t = [double]5; Write-Output (,$t); Write-Output $t',
            '$t = [int]"`t`r5`n"; Write-Output (,$t); Write-Output $t',
            "$t = [int]' 5 '; Write-Output (,$t); Write-Output $t",
            "$t = [int]''; Write-Output (,$t); Write-Output $t",
            "$t = [int]'+7'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'.5'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'0'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'007'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'0x10'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'0xFFFFFFFF'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'2.5'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'5'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'5.'; Write-Output (,$t); Write-Output $t",
            "$t = [int]'7.5'; Write-Output (,$t); Write-Output $t",
            '$t = [int]-1.5; Write-Output (,$t); Write-Output $t',
            '$t = [int]1.4; Write-Output (,$t); Write-Output $t',
            '$t = [int]1.5; Write-Output (,$t); Write-Output $t',
            '$t = [int]10d; Write-Output (,$t); Write-Output $t',
            '$t = [int]2.5; Write-Output (,$t); Write-Output $t',
            '$t = [int]5; Write-Output (,$t); Write-Output $t',
            '$t = [int][char]48; Write-Output (,$t); Write-Output $t',
            '$t = [int][char]65; Write-Output (,$t); Write-Output $t',
            '$t = [long]1.5; Write-Output (,$t); Write-Output $t',
            '$t = [long]5; Write-Output (,$t); Write-Output $t',
            "$t = [string]'foo'; Write-Output (,$t); Write-Output $t",
            "$t = [string]('a', 'b'); Write-Output (,$t); Write-Output $t",
            '$t = [string]-1.50d; Write-Output (,$t); Write-Output $t',
            '$t = [string]0.0000001; Write-Output (,$t); Write-Output $t',
            '$t = [string]0.0d; Write-Output (,$t); Write-Output $t',
            '$t = [string]0.5d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.000d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.00d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.0d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.100d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.10d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.50d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.5; Write-Output (,$t); Write-Output $t',
            '$t = [string]1.5E-7; Write-Output (,$t); Write-Output $t',
            '$t = [string]10d; Write-Output (,$t); Write-Output $t',
            '$t = [string]1E20; Write-Output (,$t); Write-Output $t',
            '$t = [string]1L; Write-Output (,$t); Write-Output $t',
            '$t = [string]2.0d; Write-Output (,$t); Write-Output $t',
            '$t = [string]5; Write-Output (,$t); Write-Output $t',
            '$t = [string]79228162514264337593543950335d; Write-Output (,$t); Write-Output $t',
            '$t = [string][uint64]18446744073709551615; Write-Output (,$t); Write-Output $t',
            "Write-Output ([string][char]65); Write-Output ([string]'A')",
            "[int]'42' + 1",
        ),
        changed=(
            "$t = 'ss' -eq [char]0x00DF; Write-Output (,$t); Write-Output $t",
            '$t = 5 -as [long]; Write-Output (,$t); Write-Output $t',
            '$t = [bool]$null; Write-Output (,$t); Write-Output $t',
            '$t = [bool](,$null); Write-Output (,$t); Write-Output $t',
            '$t = [bool]@($false); Write-Output (,$t); Write-Output $t',
            '$t = [bool]@($null); Write-Output (,$t); Write-Output $t',
            "$t = [byte]'0x80'; Write-Output (,$t); Write-Output $t",
            '$t = [char]$null; Write-Output (,$t); Write-Output $t',
            "$t = [char]'A'; Write-Output (,$t); Write-Output $t",
            "$t = [char]0x00DF -eq 'ss'; Write-Output (,$t); Write-Output $t",
            '$t = [int]$null; Write-Output (,$t); Write-Output $t',
            '$t = [int]$true; Write-Output (,$t); Write-Output $t',
            "$t = [sbyte]'0x80'; Write-Output (,$t); Write-Output $t",
            '$t = [string]$false; Write-Output (,$t); Write-Output $t',
            '$t = [string]$null; Write-Output (,$t); Write-Output $t',
            '$t = [string]$true; Write-Output (,$t); Write-Output $t',
            "$t = [uint16]'0xFFFF'; Write-Output (,$t); Write-Output $t",
        ),
    ),
    'Ps1ReflectionReads': Contribution(
        lost=(
            "Write-Output ([Text.Encoding].GetProperty('UTF8').GetValue($Null))",
            "Write-Output ([Text.Encoding].GetProperty('UTF8').GetValue($Null, $Null))",
        ),
        changed=(
            "Write-Output ([object]::ReferenceEquals([Text.Encoding].GetProperty('UTF8').GetValue($Null), [Text.Encoding]::UTF8))",
        ),
    ),
}
