#!/usr/bin/zsh

function alias-noglob {
    while read -r entrypoint; do
        alias $entrypoint="noglob $entrypoint"
    done
}

python <<EOF | alias-noglob
from importlib.metadata import entry_points
for ep in entry_points('console_scripts'):
    if ep.module_name.startswith('refinery'):
        print(ep.name)
EOF
