name: "Python Setup"
description: "Python Setup and Dependencies"
inputs:
  py:
    required: true
    description: "Target Python Version"
  os:
    required: true
    description: "Target Operating System"
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.py }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.py }}
    - name: Install Dependencies (Linux)
      if: ${{ contains(inputs.os, 'ubuntu') }}
      shell: ${{ contains(inputs.os, 'windows') && 'cmd' || 'bash' }}
      run: sudo apt-get install xclip xvfb libzbar0
    - name: Undo Windows AutoCRLF in GIT
      if: ${{ contains(inputs.os, 'windows') }}
      shell: cmd
      run: |
        git config core.eol lf
        git config core.autocrlf false
        git rm --cached -r .
        git reset --hard
    - name: Install Dependencies (MacOS)
      if: ${{ contains(inputs.os, 'macos') }}
      shell: bash
      run: brew install libmagic zbar
    - name: Install Dependencies
      shell: ${{ contains(inputs.os, 'windows') && 'cmd' || 'bash' }}
      run: |
        python -m pip install --upgrade pip
        pip install .[all]
        python -m pip install pycodestyle pyflakes pytest-xdist
        python -m pip uninstall pip
