[pytest]
markers =
    clipboard: tests that access the clipboard
    cosmetics: tests style guide and other cosmetics
    cythonized: tests that exercise potentially cythonized code
    cythonized_only: tests that require cythonized code and are skipped in pure-Python mode
filterwarnings =
    ignore::DeprecationWarning:defusedxml
    ignore::DeprecationWarning:defusedxml\..*
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
