"""
Shared utilities for PowerShell deobfuscation transforms.
"""
from __future__ import annotations

import re
import io

from refinery.lib.scripts.ps1.model import (
    Expression,
    Ps1ArrayLiteral,
    Ps1ExpandableString,
    Ps1IntegerLiteral,
    Ps1ParenExpression,
    Ps1StringLiteral,
)

_KNOWN_NAMES = {name.lower(): name for name in [
    # powershell.exe command-line parameters
    '-Command',
    '-EncodedCommand',
    '-Exec Bypass',
    '-ExecutionPolicy',
    '-File',
    '-InputFormat',
    '-NoExit',
    '-NoLogo',
    '-NoProfile',
    '-NonInter',
    '-OutputFormat',
    '-Sta',
    '-Version',
    '-Windows Hidden',
    '-WindowStyle',
    # operators
    '-As',
    '-BAnd',
    '-BNot',
    '-BOr',
    '-BXor',
    '-Contains',
    '-CReplace',
    '-Eq',
    '-GE',
    '-GT',
    '-IReplace',
    '-In',
    '-Is',
    '-IsNot',
    '-Join',
    '-LE',
    '-Like',
    '-LT',
    '-Match',
    '-NE',
    '-Not',
    '-NotContains',
    '-NotIn',
    '-NotLike',
    '-NotMatch',
    '-Replace',
    '-Shl',
    '-Shr',
    '-Split',
    '-XOr',
    # cmdlets
    'Add-Content',
    'Add-Member',
    'Add-Type',
    'Clear-Content',
    'Clear-Host',
    'Clear-Item',
    'Clear-Variable',
    'Compare-Object',
    'ConvertFrom-Base64',
    'ConvertFrom-Json',
    'ConvertFrom-SecureString',
    'ConvertFrom-StringData',
    'ConvertTo-Html',
    'ConvertTo-Json',
    'ConvertTo-SecureString',
    'Copy-Item',
    'Disable-PSRemoting',
    'Enable-PSRemoting',
    'Enter-PSSession',
    'Exit-PSSession',
    'Export-Clixml',
    'Export-Csv',
    'ForEach-Object',
    'Format-Hex',
    'Format-List',
    'Format-Table',
    'Get-Acl',
    'Get-Alias',
    'Get-ChildItem',
    'Get-CimInstance',
    'Get-Clipboard',
    'Get-Command',
    'Get-Content',
    'Get-Credential',
    'Get-Culture',
    'Get-Date',
    'Get-EventLog',
    'Get-ExecutionPolicy',
    'Get-Host',
    'Get-Item',
    'Get-ItemProperty',
    'Get-ItemPropertyValue',
    'Get-Job',
    'Get-Location',
    'Get-Member',
    'Get-Module',
    'Get-NetAdapter',
    'Get-NetIPAddress',
    'Get-Process',
    'Get-Random',
    'Get-Service',
    'Get-Variable',
    'Get-WinEvent',
    'Get-WmiObject',
    'Group-Object',
    'Import-Clixml',
    'Import-Csv',
    'Import-Module',
    'Invoke-CimMethod',
    'Invoke-Command',
    'Invoke-Expression',
    'Invoke-Item',
    'Invoke-RestMethod',
    'Invoke-WebRequest',
    'Invoke-WmiMethod',
    'Join-Path',
    'Measure-Command',
    'Measure-Object',
    'Move-Item',
    'New-Alias',
    'New-Item',
    'New-ItemProperty',
    'New-Object',
    'New-PSDrive',
    'New-PSSession',
    'New-ScheduledTask',
    'New-Service',
    'New-TimeSpan',
    'New-Variable',
    'Out-File',
    'Out-Null',
    'Out-String',
    'Read-Host',
    'Receive-Job',
    'Register-ObjectEvent',
    'Register-ScheduledTask',
    'Remove-Item',
    'Remove-ItemProperty',
    'Remove-Job',
    'Remove-Module',
    'Remove-PSDrive',
    'Remove-Variable',
    'Rename-Item',
    'Resolve-DnsName',
    'Resolve-Path',
    'Restart-Computer',
    'Restart-Service',
    'Select-Object',
    'Select-String',
    'Send-MailMessage',
    'Set-Acl',
    'Set-Alias',
    'Set-Clipboard',
    'Set-Content',
    'Set-ExecutionPolicy',
    'Set-Item',
    'Set-ItemProperty',
    'Set-Location',
    'Set-StrictMode',
    'Set-Variable',
    'Sort-Object',
    'Split-Path',
    'Start-BitsTransfer',
    'Start-Job',
    'Start-Process',
    'Start-Service',
    'Start-Sleep',
    'Start-Transcript',
    'Stop-Computer',
    'Stop-Job',
    'Stop-Process',
    'Stop-Service',
    'Stop-Transcript',
    'Tee-Object',
    'Test-Connection',
    'Test-NetConnection',
    'Test-Path',
    'Unblock-File',
    'Unregister-ScheduledTask',
    'Update-Help',
    'Wait-Job',
    'Wait-Process',
    'Where-Object',
    'Write-Debug',
    'Write-Error',
    'Write-Host',
    'Write-Output',
    'Write-Progress',
    'Write-Verbose',
    'Write-Warning',
    # .NET type names (short)
    'Array',
    'BitConverter',
    'Boolean',
    'Byte',
    'Char',
    'Console',
    'Convert',
    'DateTime',
    'Decimal',
    'Double',
    'Enum',
    'Environment',
    'EventArgs',
    'Exception',
    'Guid',
    'Hashtable',
    'Int16',
    'Int32',
    'Int64',
    'IntPtr',
    'Math',
    'Object',
    'Random',
    'Regex',
    'SByte',
    'Single',
    'String',
    'TimeSpan',
    'UInt16',
    'UInt32',
    'UInt64',
    'UIntPtr',
    'Uri',
    'Version',
    'Void',
    # .NET type names (namespace-qualified)
    'Collections.ArrayList',
    'Collections.Generic.Dictionary',
    'Collections.Generic.HashSet',
    'Collections.Generic.List',
    'Collections.Hashtable',
    'Collections.ObjectModel.Collection',
    'Collections.Queue',
    'Collections.SortedList',
    'Collections.Specialized.OrderedDictionary',
    'Collections.Stack',
    'ComponentModel.Win32Exception',
    'Diagnostics.Process',
    'Diagnostics.ProcessStartInfo',
    'Drawing.Bitmap',
    'Drawing.Graphics',
    'Drawing.Image',
    'Globalization.CultureInfo',
    'IO.BinaryReader',
    'IO.BinaryWriter',
    'IO.Compression.CompressionMode',
    'IO.Compression.DeflateStream',
    'IO.Compression.GZipStream',
    'IO.Compression.ZipFile',
    'IO.Directory',
    'IO.DirectoryInfo',
    'IO.File',
    'IO.FileInfo',
    'IO.FileMode',
    'IO.FileStream',
    'IO.MemoryStream',
    'IO.Path',
    'IO.Stream',
    'IO.StreamReader',
    'IO.StreamWriter',
    'IO.StringReader',
    'IO.StringWriter',
    'Management.Automation.PSCredential',
    'Management.Automation.ScriptBlock',
    'Management.ManagementObject',
    'Management.ManagementObjectSearcher',
    'Net.CredentialCache',
    'Net.Dns',
    'Net.HttpWebRequest',
    'Net.HttpWebResponse',
    'Net.IPAddress',
    'Net.IPEndPoint',
    'Net.Mail.MailMessage',
    'Net.Mail.SmtpClient',
    'Net.NetworkCredential',
    'Net.Security.SslStream',
    'Net.SecurityProtocolType',
    'Net.ServicePointManager',
    'Net.Sockets.NetworkStream',
    'Net.Sockets.TcpClient',
    'Net.Sockets.TcpListener',
    'Net.Sockets.UdpClient',
    'Net.WebClient',
    'Net.WebProxy',
    'Net.WebRequest',
    'Reflection.Assembly',
    'Reflection.AssemblyName',
    'Reflection.BindingFlags',
    'Reflection.Emit.AssemblyBuilderAccess',
    'Runtime.InteropServices.DllImportAttribute',
    'Runtime.InteropServices.Marshal',
    'Runtime.InteropServices.RuntimeEnvironment',
    'Security.AccessControl.FileSystemAccessRule',
    'Security.Cryptography.AesCryptoServiceProvider',
    'Security.Cryptography.AesManaged',
    'Security.Cryptography.CipherMode',
    'Security.Cryptography.CryptoStream',
    'Security.Cryptography.CryptoStreamMode',
    'Security.Cryptography.DESCryptoServiceProvider',
    'Security.Cryptography.HMACMD5',
    'Security.Cryptography.HMACSHA1',
    'Security.Cryptography.HMACSHA256',
    'Security.Cryptography.ICryptoTransform',
    'Security.Cryptography.MD5',
    'Security.Cryptography.MD5CryptoServiceProvider',
    'Security.Cryptography.PaddingMode',
    'Security.Cryptography.RNGCryptoServiceProvider',
    'Security.Cryptography.RSA',
    'Security.Cryptography.RSACryptoServiceProvider',
    'Security.Cryptography.RijndaelManaged',
    'Security.Cryptography.SHA1',
    'Security.Cryptography.SHA1Managed',
    'Security.Cryptography.SHA256',
    'Security.Cryptography.SHA256Managed',
    'Security.Cryptography.SHA384',
    'Security.Cryptography.SHA512',
    'Security.Cryptography.SymmetricAlgorithm',
    'Security.Cryptography.TripleDESCryptoServiceProvider',
    'Security.Cryptography.X509Certificates.X509Certificate2',
    'Security.Principal.WindowsBuiltInRole',
    'Security.Principal.WindowsIdentity',
    'Security.Principal.WindowsPrincipal',
    'Security.SecureString',
    'ServiceProcess.ServiceController',
    'Text.ASCIIEncoding',
    'Text.Encoding',
    'Text.RegularExpressions.Regex',
    'Text.RegularExpressions.RegexOptions',
    'Text.StringBuilder',
    'Text.UTF8Encoding',
    'Threading.Mutex',
    'Threading.Thread',
    'Threading.Timer',
    'Xml.XmlDocument',
    'Add',
    'AddArgument',
    'AddScript',
    'AppendText',
    'Clone',
    'Close',
    'CompareTo',
    'ComputeHash',
    'Contains',
    'ConvertAll',
    'Copy',
    'CopyTo',
    'Create',
    'CreateDecryptor',
    'CreateEncryptor',
    'CreateInstance',
    'CreateSubKey',
    'Decompress',
    'Decrypt',
    'DefineDynamicAssembly',
    'DefineDynamicModule',
    'DefineEnum',
    'DefineLiteral',
    'DefinePInvokeMethod',
    'DefineType',
    'Delete',
    'DeleteSubKey',
    'DeleteValue',
    'Dispose',
    'DownloadData',
    'DownloadFile',
    'DownloadString',
    'Encrypt',
    'EndsWith',
    'Equals',
    'Exists',
    'Flush',
    'Format',
    'FromBase64String',
    'GetBytes',
    'GetBuffer',
    'GetChars',
    'GetConstructor',
    'GetCurrentProcess',
    'GetDomain',
    'GetEnumerator',
    'GetEnvironmentVariable',
    'GetField',
    'GetFolderPath',
    'GetHashCode',
    'GetHostAddresses',
    'GetHostByName',
    'GetHostEntry',
    'GetHostName',
    'GetKeyNames',
    'GetMethod',
    'GetMethods',
    'GetModuleHandle',
    'GetProcAddress',
    'GetProcesses',
    'GetProcessesByName',
    'GetProperties',
    'GetProperty',
    'GetResponse',
    'GetResponseStream',
    'GetStream',
    'GetString',
    'GetTempFileName',
    'GetTempPath',
    'GetType',
    'GetTypes',
    'GetValue',
    'GetValueNames',
    'IndexOf',
    'Insert',
    'Invoke',
    'IsMatch',
    'IsNullOrEmpty',
    'IsNullOrWhiteSpace',
    'Join',
    'Kill',
    'Load',
    'LoadFile',
    'LoadFrom',
    'LoadLibrary',
    'LoadWithPartialName',
    'Match',
    'Matches',
    'Move',
    'Open',
    'OpenKey',
    'OpenRead',
    'OpenSubKey',
    'OpenText',
    'PadLeft',
    'PadRight',
    'Parse',
    'Peek',
    'Pop',
    'Push',
    'Read',
    'ReadAllBytes',
    'ReadAllLines',
    'ReadAllText',
    'ReadByte',
    'ReadLine',
    'ReadToEnd',
    'Remove',
    'Replace',
    'Reverse',
    'Seek',
    'SetEnvironmentVariable',
    'SetValue',
    'Sleep',
    'Sort',
    'Split',
    'Start',
    'StartsWith',
    'Stop',
    'Substring',
    'ToArray',
    'ToBase64String',
    'ToBoolean',
    'ToByte',
    'ToChar',
    'ToCharArray',
    'ToDouble',
    'ToInt16',
    'ToInt32',
    'ToInt64',
    'ToLower',
    'ToSingle',
    'ToString',
    'ToUInt16',
    'ToUInt32',
    'ToUInt64',
    'ToUpper',
    'TransformBlock',
    'TransformFinalBlock',
    'Trim',
    'TrimEnd',
    'TrimStart',
    'TryParse',
    'UploadData',
    'UploadFile',
    'UploadString',
    'UploadValues',
    'Write',
    'WriteAllBytes',
    'WriteAllLines',
    'WriteAllText',
    'WriteByte',
    'WriteLine',
    # properties
    'Address',
    'Assembly',
    'BaseStream',
    'BlockSize',
    'CanRead',
    'CanSeek',
    'CanWrite',
    'ChildItem',
    'Command',
    'ContentType',
    'Count',
    'Credentials',
    'Current',
    'CurrentDomain',
    'Data',
    'Definition',
    'DirectoryName',
    'EntryPoint',
    'ExitCode',
    'Extension',
    'FullName',
    'HasExited',
    'Headers',
    'Id',
    'IV',
    'IsPresent',
    'Item',
    'Key',
    'KeySize',
    'Keys',
    'Length',
    'Location',
    'MainModule',
    'Message',
    'Method',
    'Mode',
    'Modules',
    'Name',
    'OperatingSystem',
    'PSVersionTable',
    'Padding',
    'Path',
    'Position',
    'PowerShell',
    'ProcessName',
    'ProcessorArchitecture',
    'Protocol',
    'Proxy',
    'ResponseUri',
    'Result',
    'Size',
    'StandardOutput',
    'StatusCode',
    'Text',
    'UserAgent',
    'Value',
    'Values',
]}

KEYWORD_SPELLING: dict[str, str] = {
    'param': 'Param',
}

_SIMPLE_IDENT = re.compile(r'^[a-zA-Z_]\w*$')


def _string_value(node: Expression) -> str | None:
    if isinstance(node, Ps1StringLiteral):
        return node.value
    if isinstance(node, Ps1ExpandableString):
        out = io.StringIO()
        for p in node.parts:
            if not isinstance(p, Ps1StringLiteral):
                break
            out.write(p.value)
        else:
            return out.getvalue()
    return None


def _make_string_literal(value: str) -> Ps1StringLiteral:
    if "'" not in value:
        raw = F"'{value}'"
    elif '"' not in value and '$' not in value and '`' not in value:
        raw = F'"{value}"'
    else:
        raw = "'" + value.replace("'", "''") + "'"
    return Ps1StringLiteral(value=value, raw=raw)


def _collect_string_arguments(node: Expression) -> list[str] | None:
    if isinstance(node, Ps1ArrayLiteral):
        result = []
        for elem in node.elements:
            sv = _string_value(elem)
            if sv is None:
                return None
            result.append(sv)
        return result
    sv = _string_value(node)
    if sv is not None:
        return [sv]
    return None


def _collect_int_arguments(node: Expression) -> list[int] | None:
    if isinstance(node, Ps1ArrayLiteral):
        result = []
        for elem in node.elements:
            if not isinstance(elem, Ps1IntegerLiteral):
                return None
            result.append(elem.value)
        return result
    if isinstance(node, Ps1ParenExpression) and node.expression is not None:
        return _collect_int_arguments(node.expression)
    if isinstance(node, Ps1IntegerLiteral):
        return [node.value]
    return None


def _unwrap_paren_to_array(node: Expression) -> Expression:
    if isinstance(node, Ps1ParenExpression) and node.expression is not None:
        return node.expression
    return node


def _case_normalize_name(name: str) -> str:
    lower = name.lower()
    canonical = _KNOWN_NAMES.get(lower)
    if canonical is not None:
        return canonical
    return name
