name: publish

on:
  push:
    tags: '[0-9]+\.*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      MALSHARE_API: ${{ secrets.MALSHARE_API }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']
        os: [windows-latest, macos-13, ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      uses: ./.github/actions/setup/
      with:
        py: ${{ matrix.python-version }}
        os: ${{ matrix.os }}
    - name: Run Tests
      uses: ./.github/actions/test/
      with:
        py: ${{ matrix.python-version }}
        os: ${{ matrix.os }}

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Build package
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m build --sdist
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
